"""
Fuzzy exercise name matching for Garmin workouts.

This module provides intelligent matching from user-friendly exercise names
(e.g., "bench press", "dumbbell curl") to Garmin's required SCREAMING_SNAKE_CASE
format (e.g., BARBELL_BENCH_PRESS, DUMBBELL_BICEPS_CURL).

Example:
    >>> from garmy.workouts.exercises import ExerciseMatcher
    >>> matcher = ExerciseMatcher()
    >>> result = matcher.resolve("bench press")
    >>> result.name
    'BARBELL_BENCH_PRESS'
    >>> result.category
    'BENCH_PRESS'
"""

from dataclasses import dataclass, field
from difflib import SequenceMatcher
from typing import Dict, List, Optional, Set, Tuple
import re


@dataclass(frozen=True)
class MatchResult:
    """Result of fuzzy exercise name matching.

    Attributes:
        name: Garmin exercise name in SCREAMING_SNAKE_CASE
        category: Garmin exercise category
        score: Match confidence score (0.0 to 1.0)
        alternatives: Other potential matches with their scores
    """

    name: str
    category: str
    score: float
    alternatives: List[Tuple[str, str, float]] = field(default_factory=list)

    @property
    def is_exact(self) -> bool:
        """True if this was an exact match."""
        return self.score >= 1.0

    @property
    def is_confident(self) -> bool:
        """True if confidence is high enough to use without warning."""
        return self.score >= 0.8

    def __str__(self) -> str:
        return f"{self.name} ({self.score:.0%})"


# =============================================================================
# EXERCISE DATABASE
# =============================================================================
# Format: { "EXERCISE_NAME": "CATEGORY" }
# Populated from Garmin FIT SDK Profile
# =============================================================================

EXERCISES: Dict[str, str] = {
    # =========================================================================
    # BENCH_PRESS Category (Chest Press Movements)
    # =========================================================================
    "ALTERNATING_DUMBBELL_CHEST_PRESS": "BENCH_PRESS",
    "ALTERNATING_DUMBBELL_CHEST_PRESS_ON_SWISS_BALL": "BENCH_PRESS",
    "BARBELL_BENCH_PRESS": "BENCH_PRESS",
    "BARBELL_BOARD_BENCH_PRESS": "BENCH_PRESS",
    "BARBELL_FLOOR_PRESS": "BENCH_PRESS",
    "CLOSE_GRIP_BARBELL_BENCH_PRESS": "BENCH_PRESS",
    "DECLINE_DUMBBELL_BENCH_PRESS": "BENCH_PRESS",
    "DUMBBELL_BENCH_PRESS": "BENCH_PRESS",
    "DUMBBELL_FLOOR_PRESS": "BENCH_PRESS",
    "INCLINE_BARBELL_BENCH_PRESS": "BENCH_PRESS",
    "INCLINE_DUMBBELL_BENCH_PRESS": "BENCH_PRESS",
    "INCLINE_SMITH_MACHINE_BENCH_PRESS": "BENCH_PRESS",
    "ISOMETRIC_BARBELL_BENCH_PRESS": "BENCH_PRESS",
    "KETTLEBELL_CHEST_PRESS": "BENCH_PRESS",
    "NEUTRAL_GRIP_DUMBBELL_BENCH_PRESS": "BENCH_PRESS",
    "NEUTRAL_GRIP_DUMBBELL_INCLINE_BENCH_PRESS": "BENCH_PRESS",
    "ONE_ARM_FLOOR_PRESS": "BENCH_PRESS",
    "WEIGHTED_ONE_ARM_FLOOR_PRESS": "BENCH_PRESS",
    "PARTIAL_LOCKOUT": "BENCH_PRESS",
    "REVERSE_GRIP_BARBELL_BENCH_PRESS": "BENCH_PRESS",
    "REVERSE_GRIP_INCLINE_BENCH_PRESS": "BENCH_PRESS",
    "SINGLE_ARM_CABLE_CHEST_PRESS": "BENCH_PRESS",
    "SINGLE_ARM_DUMBBELL_BENCH_PRESS": "BENCH_PRESS",
    "SMITH_MACHINE_BENCH_PRESS": "BENCH_PRESS",
    "SWISS_BALL_DUMBBELL_CHEST_PRESS": "BENCH_PRESS",
    "TRIPLE_STOP_BARBELL_BENCH_PRESS": "BENCH_PRESS",
    "WIDE_GRIP_BARBELL_BENCH_PRESS": "BENCH_PRESS",
    "BENCH_PRESS": "BENCH_PRESS",
    "WEIGHTED_BENCH_PRESS": "BENCH_PRESS",
    # =========================================================================
    # DEADLIFT Category
    # =========================================================================
    "BARBELL_DEADLIFT": "DEADLIFT",
    "BARBELL_STRAIGHT_LEG_DEADLIFT": "DEADLIFT",
    "DUMBBELL_DEADLIFT": "DEADLIFT",
    "DUMBBELL_SINGLE_LEG_DEADLIFT_TO_ROW": "DEADLIFT",
    "DUMBBELL_STRAIGHT_LEG_DEADLIFT": "DEADLIFT",
    "KETTLEBELL_FLOOR_TO_SHELF": "DEADLIFT",
    "KETTLEBELL_DEADLIFT": "DEADLIFT",
    "KETTLEBELL_SUMO_DEADLIFT": "DEADLIFT",
    "ONE_ARM_ONE_LEG_DEADLIFT": "DEADLIFT",
    "RACK_PULL": "DEADLIFT",
    "ROTATIONAL_DUMBBELL_STRAIGHT_LEG_DEADLIFT": "DEADLIFT",
    "SINGLE_ARM_DEADLIFT": "DEADLIFT",
    "SINGLE_LEG_BARBELL_DEADLIFT": "DEADLIFT",
    "SINGLE_LEG_BARBELL_STRAIGHT_LEG_DEADLIFT": "DEADLIFT",
    "SINGLE_LEG_DEADLIFT_WITH_BARBELL": "DEADLIFT",
    "SINGLE_LEG_RDL_CIRCUIT": "DEADLIFT",
    "SINGLE_LEG_ROMANIAN_DEADLIFT_CIRCUIT": "DEADLIFT",
    "SINGLE_LEG_ROMANIAN_DEADLIFT_WITH_DUMBBELL": "DEADLIFT",
    "SUMO_DEADLIFT": "DEADLIFT",
    "SUMO_DEADLIFT_HIGH_PULL": "DEADLIFT",
    "TRAP_BAR_DEADLIFT": "DEADLIFT",
    "WIDE_GRIP_BARBELL_DEADLIFT": "DEADLIFT",
    "DEADLIFT": "DEADLIFT",
    "WEIGHTED_DEADLIFT": "DEADLIFT",
    "ROMANIAN_DEADLIFT": "DEADLIFT",
    "STIFF_LEG_DEADLIFT": "DEADLIFT",
    "STRAIGHT_LEG_DEADLIFT": "DEADLIFT",
    # =========================================================================
    # SQUAT Category
    # =========================================================================
    "AIR_SQUAT": "SQUAT",
    "BACK_SQUAT_WITH_BODY_BAR": "SQUAT",
    "BACK_SQUATS": "SQUAT",
    "WEIGHTED_BACK_SQUATS": "SQUAT",
    "BALANCING_SQUAT": "SQUAT",
    "WEIGHTED_BALANCING_SQUAT": "SQUAT",
    "BARBELL_BACK_SQUAT": "SQUAT",
    "BARBELL_BOX_SQUAT": "SQUAT",
    "BARBELL_FRONT_SQUAT": "SQUAT",
    "BARBELL_HACK_SQUAT": "SQUAT",
    "BARBELL_HANG_SQUAT_SNATCH": "SQUAT",
    "BARBELL_LATERAL_STEP_UP": "SQUAT",
    "BARBELL_QUARTER_SQUAT": "SQUAT",
    "BARBELL_SIFF_SQUAT": "SQUAT",
    "BARBELL_SQUAT_SNATCH": "SQUAT",
    "BARBELL_SQUAT_WITH_HEELS_RAISED": "SQUAT",
    "BARBELL_STEPOVER": "SQUAT",
    "BARBELL_STEP_UP": "SQUAT",
    "BENCH_SQUAT_WITH_ROTATIONAL_CHOP": "SQUAT",
    "BODY_WEIGHT_WALL_SQUAT": "SQUAT",
    "WEIGHTED_WALL_SQUAT": "SQUAT",
    "BOX_STEP_SQUAT": "SQUAT",
    "BRACED_SQUAT": "SQUAT",
    "CROSSED_ARM_BARBELL_FRONT_SQUAT": "SQUAT",
    "CROSSOVER_DUMBBELL_STEP_UP": "SQUAT",
    "DUMBBELL_FRONT_SQUAT": "SQUAT",
    "DUMBBELL_SPLIT_SQUAT": "SQUAT",
    "DUMBBELL_SQUAT": "SQUAT",
    "DUMBBELL_SQUAT_CLEAN": "SQUAT",
    "DUMBBELL_SQUAT_SNATCH": "SQUAT",
    "DUMBBELL_STEPOVER": "SQUAT",
    "DUMBBELL_STEP_UP": "SQUAT",
    "DUMBBELL_THRUSTERS": "SQUAT",
    "ELEVATED_SINGLE_LEG_SQUAT": "SQUAT",
    "FIGURE_FOUR_SQUATS": "SQUAT",
    "GOBLET_SQUAT": "SQUAT",
    "KETTLEBELL_SQUAT": "SQUAT",
    "KETTLEBELL_SWING_OVERHEAD": "SQUAT",
    "KETTLEBELL_SWING_WITH_FLIP_TO_SQUAT": "SQUAT",
    "LATERAL_DUMBBELL_STEP_UP": "SQUAT",
    "LEG_PRESS": "SQUAT",
    "MEDICINE_BALL_SQUAT": "SQUAT",
    "ONE_LEGGED_SQUAT": "SQUAT",
    "OVERHEAD_BARBELL_SQUAT": "SQUAT",
    "OVERHEAD_DUMBBELL_SQUAT": "SQUAT",
    "OVERHEAD_SQUAT": "SQUAT",
    "PARTIAL_SINGLE_LEG_SQUAT": "SQUAT",
    "PISTOL_SQUAT": "SQUAT",
    "PLIE_SLIDES": "SQUAT",
    "PLIE_SQUAT": "SQUAT",
    "PRISONER_SQUAT": "SQUAT",
    "SINGLE_LEG_BENCH_GET_UP": "SQUAT",
    "SINGLE_LEG_BENCH_SQUAT": "SQUAT",
    "SINGLE_LEG_SQUAT_ON_SWISS_BALL": "SQUAT",
    "SQUAT": "SQUAT",
    "WEIGHTED_SQUAT": "SQUAT",
    "SQUATS_WITH_BAND": "SQUAT",
    "SQUAT_AND_SIDE_KICK": "SQUAT",
    "SQUAT_JUMPS_IN_N_OUT": "SQUAT",
    "STAGGERED_SQUAT": "SQUAT",
    "STEP_UP": "SQUAT",
    "SUITCASE_SQUATS": "SQUAT",
    "SUMO_SQUAT": "SQUAT",
    "SUMO_SQUAT_SLIDE_IN": "SQUAT",
    "SUMO_SQUAT_TO_HIGH_PULL": "SQUAT",
    "SUMO_SQUAT_TO_STAND": "SQUAT",
    "SUMO_SQUAT_WITH_ROTATION": "SQUAT",
    "SWISS_BALL_BODY_WEIGHT_WALL_SQUAT": "SQUAT",
    "THRUSTERS": "SQUAT",
    "UNEVEN_SQUAT": "SQUAT",
    "WAIST_SLIMMING_SQUAT": "SQUAT",
    "WALL_BALL": "SQUAT",
    "WALL_BALL_SQUAT_AND_PRESS": "SQUAT",
    "WIDE_STANCE_BARBELL_SQUAT": "SQUAT",
    "WIDE_STANCE_GOBLET_SQUAT": "SQUAT",
    "ZERCHER_SQUAT": "SQUAT",
    "FRONT_SQUAT": "SQUAT",
    "HACK_SQUAT": "SQUAT",
    "JUMP_SQUAT": "SQUAT",
    "SPLIT_SQUAT": "SQUAT",
    "BOX_SQUAT": "SQUAT",
    "PAUSE_SQUAT": "SQUAT",
    "BULGARIAN_SPLIT_SQUAT": "SQUAT",
    "ALTERNATING_BOX_DUMBBELL_STEP_UPS": "SQUAT",
    "SQUAT_AMERICAN_SWING": "SQUAT",
    # =========================================================================
    # CURL Category (Biceps)
    # =========================================================================
    "ALTERNATING_DUMBBELL_BICEPS_CURL": "CURL",
    "ALTERNATING_DUMBBELL_BICEPS_CURL_ON_SWISS_BALL": "CURL",
    "ALTERNATING_INCLINE_DUMBBELL_BICEPS_CURL": "CURL",
    "BARBELL_BICEPS_CURL": "CURL",
    "BARBELL_REVERSE_WRIST_CURL": "CURL",
    "BARBELL_WRIST_CURL": "CURL",
    "BEHIND_THE_BACK_BARBELL_REVERSE_WRIST_CURL": "CURL",
    "BEHIND_THE_BACK_ONE_ARM_CABLE_CURL": "CURL",
    "CABLE_BICEPS_CURL": "CURL",
    "CABLE_HAMMER_CURL": "CURL",
    "CHEATING_BARBELL_BICEPS_CURL": "CURL",
    "CLOSE_GRIP_EZ_BAR_BICEPS_CURL": "CURL",
    "CROSS_BODY_DUMBBELL_HAMMER_CURL": "CURL",
    "DEAD_HANG_BICEPS_CURL": "CURL",
    "DECLINE_HAMMER_CURL": "CURL",
    "DUMBBELL_BICEPS_CURL": "CURL",
    "DUMBBELL_BICEPS_CURL_WITH_STATIC_HOLD": "CURL",
    "DUMBBELL_HAMMER_CURL": "CURL",
    "DUMBBELL_REVERSE_WRIST_CURL": "CURL",
    "DUMBBELL_WRIST_CURL": "CURL",
    "EZ_BAR_PREACHER_CURL": "CURL",
    "FORWARD_BEND_BICEPS_CURL": "CURL",
    "HAMMER_CURL_TO_PRESS": "CURL",
    "INCLINE_DUMBBELL_BICEPS_CURL": "CURL",
    "INCLINE_OFFSET_THUMB_DUMBBELL_CURL": "CURL",
    "KETTLEBELL_BICEPS_CURL": "CURL",
    "LYING_CONCENTRATION_CABLE_CURL": "CURL",
    "ONE_ARM_CONCENTRATION_CURL": "CURL",
    "ONE_ARM_PREACHER_CURL": "CURL",
    "PLATE_PINCH_CURL": "CURL",
    "PREACHER_CURL_WITH_CABLE": "CURL",
    "REVERSE_EZ_BAR_CURL": "CURL",
    "REVERSE_GRIP_BARBELL_BICEPS_CURL": "CURL",
    "REVERSE_GRIP_WRIST_CURL": "CURL",
    "SEATED_ALTERNATING_DUMBBELL_BICEPS_CURL": "CURL",
    "SEATED_DUMBBELL_BICEPS_CURL": "CURL",
    "SEATED_REVERSE_DUMBBELL_CURL": "CURL",
    "SPLIT_STANCE_OFFSET_PINKY_DUMBBELL_CURL": "CURL",
    "STANDING_ALTERNATING_DUMBBELL_CURLS": "CURL",
    "STANDING_DUMBBELL_BICEPS_CURL": "CURL",
    "STANDING_EZ_BAR_BICEPS_CURL": "CURL",
    "STANDING_ZOTTMAN_BICEPS_CURL": "CURL",
    "STATIC_CURL": "CURL",
    "SWISS_BALL_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION": "CURL",
    "SWISS_BALL_EZ_BAR_PREACHER_CURL": "CURL",
    "TWISTING_STANDING_DUMBBELL_BICEPS_CURL": "CURL",
    "WIDE_GRIP_EZ_BAR_BICEPS_CURL": "CURL",
    "BICEPS_CURL": "CURL",
    "HAMMER_CURL": "CURL",
    "PREACHER_CURL": "CURL",
    "CONCENTRATION_CURL": "CURL",
    "SPIDER_CURL": "CURL",
    "ZOTTMAN_CURL": "CURL",
    "INCLINE_CURL": "CURL",
    "CABLE_CURL": "CURL",
    "DRAG_CURL": "CURL",
    "WRIST_CURL": "CURL",
    "REVERSE_CURL": "CURL",
    # =========================================================================
    # ROW Category
    # =========================================================================
    "ALTERNATING_DUMBBELL_ROW": "ROW",
    "BANDED_FACE_PULLS": "ROW",
    "BARBELL_ROW": "ROW",
    "BARBELL_STRAIGHT_LEG_DEADLIFT_TO_ROW": "ROW",
    "BENT_OVER_ROW_WITH_BARBELL": "ROW",
    "BENT_OVER_ROW_WITH_DUMBBELL": "ROW",
    "CABLE_ROW_STANDING": "ROW",
    "CHEST_SUPPORTED_DUMBBELL_ROW": "ROW",
    "DECLINE_RING_ROW": "ROW",
    "DUMBBELL_ROW": "ROW",
    "ELEVATED_FEET_INVERTED_ROW": "ROW",
    "ELEVATED_RING_ROW": "ROW",
    "FACE_PULL": "ROW",
    "FACE_PULL_WITH_EXTERNAL_ROTATION": "ROW",
    "INDOOR_ROW": "ROW",
    "INVERTED_ROW": "ROW",
    "INVERTED_ROW_WITH_FEET_ON_SWISS_BALL": "ROW",
    "KETTLEBELL_ROW": "ROW",
    "MODIFIED_INVERTED_ROW": "ROW",
    "NEUTRAL_GRIP_ALTERNATING_DUMBBELL_ROW": "ROW",
    "ONE_ARM_BENT_OVER_ROW": "ROW",
    "ONE_LEGGED_DUMBBELL_ROW": "ROW",
    "RDL_BENT_OVER_ROW_WITH_BARBELL_DUMBBELL": "ROW",
    "RENEGADE_ROW": "ROW",
    "REVERSE_GRIP_BARBELL_ROW": "ROW",
    "RING_ROW": "ROW",
    "ROPE_HANDLE_CABLE_ROW": "ROW",
    "ROW": "ROW",
    "WEIGHTED_ROW": "ROW",
    "SEATED_CABLE_ROW": "ROW",
    "SEATED_DUMBBELL_ROW": "ROW",
    "SEATED_UNDERHAND_GRIP_CABLE_ROW": "ROW",
    "SINGLE_ARM_CABLE_ROW": "ROW",
    "SINGLE_ARM_CABLE_ROW_AND_ROTATION": "ROW",
    "SINGLE_ARM_INVERTED_ROW": "ROW",
    "SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW": "ROW",
    "SINGLE_ARM_NEUTRAL_GRIP_DUMBBELL_ROW_AND_ROTATION": "ROW",
    "SUSPENDED_INVERTED_ROW": "ROW",
    "T_BAR_ROW": "ROW",
    "TOWEL_GRIP_INVERTED_ROW": "ROW",
    "TRX_INVERTED_ROW": "ROW",
    "UNDERHAND_GRIP_CABLE_ROW": "ROW",
    "V_GRIP_CABLE_ROW": "ROW",
    "WIDE_GRIP_SEATED_CABLE_ROW": "ROW",
    "BENT_OVER_ROW": "ROW",
    "PENDLAY_ROW": "ROW",
    "YATES_ROW": "ROW",
    "MEADOWS_ROW": "ROW",
    "GORILLA_ROW": "ROW",
    "SEAL_ROW": "ROW",
    "KROC_ROW": "ROW",
    # =========================================================================
    # LUNGE Category
    # =========================================================================
    "ALTERNATING_BARBELL_FORWARD_LUNGE": "LUNGE",
    "ALTERNATING_DUMBBELL_LUNGE_WITH_REACH": "LUNGE",
    "BACK_FOOT_ELEVATED_DUMBBELL_SPLIT_SQUAT": "LUNGE",
    "BARBELL_BOX_LUNGE": "LUNGE",
    "BARBELL_BULGARIAN_SPLIT_SQUAT": "LUNGE",
    "BARBELL_CROSSOVER_LUNGE": "LUNGE",
    "BARBELL_FRONT_SPLIT_SQUAT": "LUNGE",
    "BARBELL_LUNGE": "LUNGE",
    "BARBELL_REVERSE_LUNGE": "LUNGE",
    "BARBELL_SIDE_LUNGE": "LUNGE",
    "BARBELL_SPLIT_SQUAT": "LUNGE",
    "CORE_CONTROL_REAR_LUNGE": "LUNGE",
    "CURTSY_LUNGE": "LUNGE",
    "DIAGONAL_LUNGE": "LUNGE",
    "DROP_LUNGE": "LUNGE",
    "DUMBBELL_BOX_LUNGE": "LUNGE",
    "DUMBBELL_BULGARIAN_SPLIT_SQUAT": "LUNGE",
    "DUMBBELL_CROSSOVER_LUNGE": "LUNGE",
    "DUMBBELL_DIAGONAL_LUNGE": "LUNGE",
    "DUMBBELL_LUNGE": "LUNGE",
    "DUMBBELL_LUNGE_AND_ROTATION": "LUNGE",
    "DUMBBELL_OVERHEAD_BULGARIAN_SPLIT_SQUAT": "LUNGE",
    "DUMBBELL_OVERHEAD_WALKING_LUNGE": "LUNGE",
    "DUMBBELL_REVERSE_LUNGE": "LUNGE",
    "DUMBBELL_REVERSE_LUNGE_TO_HIGH_KNEE_AND_PRESS": "LUNGE",
    "DUMBBELL_SIDE_LUNGE": "LUNGE",
    "ELEVATED_FRONT_FOOT_BARBELL_SPLIT_SQUAT": "LUNGE",
    "ELEVATED_FRONT_FOOT_DUMBBELL_SPLIT_SQUAT": "LUNGE",
    "FORWARD_LUNGE": "LUNGE",
    "FORWARD_SLIDE_LUNGE": "LUNGE",
    "FRONT_FOOT_ELEVATED_LUNGE": "LUNGE",
    "FRONT_LUNGE": "LUNGE",
    "GUN_SLINGER_LUNGE": "LUNGE",
    "LUNGE": "LUNGE",
    "WEIGHTED_LUNGE": "LUNGE",
    "LUNGE_MATRIX": "LUNGE",
    "LUNGE_WITH_ARM_REACH": "LUNGE",
    "LUNGE_WITH_DIAGONAL_REACH": "LUNGE",
    "LUNGE_WITH_SIDE_BEND": "LUNGE",
    "OFFSET_DUMBBELL_LUNGE": "LUNGE",
    "OFFSET_DUMBBELL_REVERSE_LUNGE": "LUNGE",
    "OVERHEAD_BARBELL_REVERSE_LUNGE": "LUNGE",
    "OVERHEAD_BARBELL_SPLIT_SQUAT": "LUNGE",
    "OVERHEAD_DUMBBELL_REVERSE_LUNGE": "LUNGE",
    "OVERHEAD_DUMBBELL_SPLIT_SQUAT": "LUNGE",
    "OVERHEAD_LUNGE": "LUNGE",
    "OVERHEAD_LUNGE_WITH_ROTATION": "LUNGE",
    "REAR_LUNGE": "LUNGE",
    "REVERSE_BARBELL_BOX_LUNGE": "LUNGE",
    "REVERSE_BOX_LUNGE": "LUNGE",
    "REVERSE_DUMBBELL_BOX_LUNGE": "LUNGE",
    "REVERSE_DUMBBELL_CROSSOVER_LUNGE": "LUNGE",
    "REVERSE_DUMBBELL_DIAGONAL_LUNGE": "LUNGE",
    "REVERSE_LUNGE": "LUNGE",
    "REVERSE_LUNGE_WITH_REACH_BACK": "LUNGE",
    "REVERSE_LUNGE_WITH_TWIST_AND_OVERHEAD_REACH": "LUNGE",
    "REVERSE_SLIDING_BOX_LUNGE": "LUNGE",
    "REVERSE_SLIDING_LUNGE": "LUNGE",
    "RUNNERS_LUNGE_TO_BALANCE": "LUNGE",
    "SCISSOR_POWER_SWITCH": "LUNGE",
    "SHIFTING_SIDE_LUNGE": "LUNGE",
    "SIDE_AND_CROSSOVER_LUNGE": "LUNGE",
    "SIDE_LUNGE": "LUNGE",
    "WEIGHTED_SIDE_LUNGE": "LUNGE",
    "SIDE_LUNGE_AND_PRESS": "LUNGE",
    "SIDE_LUNGE_JUMP_OFF": "LUNGE",
    "SIDE_LUNGE_SWEEP": "LUNGE",
    "SIDE_LUNGE_TDL": "LUNGE",
    "SIDE_LUNGE_TO_CROSSOVER_TAP": "LUNGE",
    "SIDE_TO_SIDE_LUNGE_CHOPS": "LUNGE",
    "SIFF_JUMP_LUNGE": "LUNGE",
    "SINGLE_ARM_REVERSE_LUNGE_AND_PRESS": "LUNGE",
    "SLIDING_LATERAL_LUNGE": "LUNGE",
    "SPLIT_BULGARIAN_SQUAT": "LUNGE",
    "WALKING_BARBELL_LUNGE": "LUNGE",
    "WALKING_DUMBBELL_LUNGE": "LUNGE",
    "WALKING_LUNGE": "LUNGE",
    "WEIGHTED_WALKING_LUNGE": "LUNGE",
    "ALTERNATING_DUMBBELL_LUNGE": "LUNGE",
    "LATERAL_LUNGE": "LUNGE",
    "STEP_THROUGH_LUNGE": "LUNGE",
    "JUMPING_LUNGE": "LUNGE",
    # =========================================================================
    # SHOULDER_PRESS Category
    # =========================================================================
    "ALTERNATING_DUMBBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "ARNOLD_PRESS": "SHOULDER_PRESS",
    "BARBELL_FRONT_SQUAT_TO_PUSH_PRESS": "SHOULDER_PRESS",
    "BARBELL_PUSH_PRESS": "SHOULDER_PRESS",
    "BARBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "DEAD_CURL_PRESS": "SHOULDER_PRESS",
    "DUMBBELL_ALTERNATING_SHOULDER_PRESS_AND_TWIST": "SHOULDER_PRESS",
    "DUMBBELL_HAMMER_CURL_TO_LUNGE_TO_PRESS": "SHOULDER_PRESS",
    "DUMBBELL_PUSH_PRESS": "SHOULDER_PRESS",
    "DUMBBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "FLOOR_INVERTED_SHOULDER_PRESS": "SHOULDER_PRESS",
    "INVERTED_SHOULDER_PRESS": "SHOULDER_PRESS",
    "KETTLEBELL_PUSH_PRESS": "SHOULDER_PRESS",
    "KETTLEBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "LANDMINE_PRESS": "SHOULDER_PRESS",
    "ONE_ARM_PUSH_PRESS": "SHOULDER_PRESS",
    "OVERHEAD_BARBELL_PRESS": "SHOULDER_PRESS",
    "OVERHEAD_DUMBBELL_PRESS": "SHOULDER_PRESS",
    "SEATED_BARBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "SEATED_DUMBBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "SINGLE_ARM_DUMBBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "SINGLE_ARM_STEP_UP_AND_PRESS": "SHOULDER_PRESS",
    "SMITH_MACHINE_OVERHEAD_PRESS": "SHOULDER_PRESS",
    "SPLIT_STANCE_HAMMER_CURL_TO_PRESS": "SHOULDER_PRESS",
    "SWISS_BALL_DUMBBELL_SHOULDER_PRESS": "SHOULDER_PRESS",
    "WEIGHT_PLATE_FRONT_RAISE": "SHOULDER_PRESS",
    "SHOULDER_PRESS": "SHOULDER_PRESS",
    "WEIGHTED_SHOULDER_PRESS": "SHOULDER_PRESS",
    "MILITARY_PRESS": "SHOULDER_PRESS",
    "OVERHEAD_PRESS": "SHOULDER_PRESS",
    "PUSH_PRESS": "SHOULDER_PRESS",
    "STRICT_PRESS": "SHOULDER_PRESS",
    "Z_PRESS": "SHOULDER_PRESS",
    "VIKING_PRESS": "SHOULDER_PRESS",
    "LOG_PRESS": "SHOULDER_PRESS",
    "BEHIND_NECK_PRESS": "SHOULDER_PRESS",
    # =========================================================================
    # LATERAL_RAISE Category
    # =========================================================================
    "45_DEGREE_CABLE_EXTERNAL_ROTATION": "LATERAL_RAISE",
    "ALTERNATING_LATERAL_RAISE_WITH_STATIC_HOLD": "LATERAL_RAISE",
    "BAR_MUSCLE_UP": "LATERAL_RAISE",
    "BENT_OVER_LATERAL_RAISE": "LATERAL_RAISE",
    "CABLE_DIAGONAL_RAISE": "LATERAL_RAISE",
    "CABLE_FRONT_RAISE": "LATERAL_RAISE",
    "CALORIE_ROW": "LATERAL_RAISE",
    "COMBO_SHOULDER_RAISE": "LATERAL_RAISE",
    "DUMBBELL_DIAGONAL_RAISE": "LATERAL_RAISE",
    "DUMBBELL_V_RAISE": "LATERAL_RAISE",
    "FRONT_RAISE": "LATERAL_RAISE",
    "LEANING_DUMBBELL_LATERAL_RAISE": "LATERAL_RAISE",
    "LYING_DUMBBELL_RAISE": "LATERAL_RAISE",
    "MUSCLE_UP": "LATERAL_RAISE",
    "ONE_ARM_CABLE_LATERAL_RAISE": "LATERAL_RAISE",
    "OVERHAND_GRIP_REAR_LATERAL_RAISE": "LATERAL_RAISE",
    "PLATE_RAISES": "LATERAL_RAISE",
    "RING_DIP": "LATERAL_RAISE",
    "RING_MUSCLE_UP": "LATERAL_RAISE",
    "ROPE_CLIMB": "LATERAL_RAISE",
    "SCAPTION": "LATERAL_RAISE",
    "SCAPTION_AND_SHRUG": "LATERAL_RAISE",
    "SEATED_LATERAL_RAISE": "LATERAL_RAISE",
    "SEATED_REAR_LATERAL_RAISE": "LATERAL_RAISE",
    "SIDE_LYING_LATERAL_RAISE": "LATERAL_RAISE",
    "STANDING_LIFT": "LATERAL_RAISE",
    "SUSPENDED_ROW": "LATERAL_RAISE",
    "UNDERHAND_GRIP_REAR_LATERAL_RAISE": "LATERAL_RAISE",
    "WALL_SLIDE": "LATERAL_RAISE",
    "WEIGHTED_WALL_SLIDE": "LATERAL_RAISE",
    "LATERAL_RAISE": "LATERAL_RAISE",
    "WEIGHTED_LATERAL_RAISE": "LATERAL_RAISE",
    "ARM_CIRCLES": "LATERAL_RAISE",
    "DUMBBELL_FRONT_RAISE": "LATERAL_RAISE",
    "CABLE_LATERAL_RAISE": "LATERAL_RAISE",
    "REAR_DELT_FLY": "LATERAL_RAISE",
    "DUMBBELL_LATERAL_RAISE": "LATERAL_RAISE",
    "UPRIGHT_ROW": "LATERAL_RAISE",
    # =========================================================================
    # TRICEPS_EXTENSION Category
    # =========================================================================
    "BENCH_DIP": "TRICEPS_EXTENSION",
    "WEIGHTED_BENCH_DIP": "TRICEPS_EXTENSION",
    "BODY_WEIGHT_DIP": "TRICEPS_EXTENSION",
    "CABLE_KICKBACK": "TRICEPS_EXTENSION",
    "CABLE_LYING_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "CABLE_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "DUMBBELL_KICKBACK": "TRICEPS_EXTENSION",
    "DUMBBELL_LYING_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "EZ_BAR_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "INCLINE_DIP": "TRICEPS_EXTENSION",
    "WEIGHTED_INCLINE_DIP": "TRICEPS_EXTENSION",
    "INCLINE_EZ_BAR_LYING_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "LYING_DUMBBELL_PULLOVER_TO_EXTENSION": "TRICEPS_EXTENSION",
    "LYING_EZ_BAR_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "LYING_TRICEPS_EXTENSION_TO_CLOSE_GRIP_BENCH_PRESS": "TRICEPS_EXTENSION",
    "NEUTRAL_GRIP_TRICEPS_PUSHDOWN": "TRICEPS_EXTENSION",
    "OVERHEAD_DUMBBELL_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "PRONATED_GRIP_TRICEPS_PUSHDOWN": "TRICEPS_EXTENSION",
    "REVERSE_GRIP_TRICEPS_PUSHDOWN": "TRICEPS_EXTENSION",
    "ROPE_PUSHDOWN": "TRICEPS_EXTENSION",
    "SEATED_BARBELL_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "SEATED_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "SEATED_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "SEATED_SINGLE_ARM_OVERHEAD_DUMBBELL_EXTENSION": "TRICEPS_EXTENSION",
    "SINGLE_ARM_DUMBBELL_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "SINGLE_DUMBBELL_SEATED_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "STATIC_LYING_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "SUSPENDED_DIP": "TRICEPS_EXTENSION",
    "WEIGHTED_SUSPENDED_DIP": "TRICEPS_EXTENSION",
    "SWISS_BALL_DUMBBELL_LYING_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "SWISS_BALL_EZ_BAR_LYING_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "SWISS_BALL_EZ_BAR_OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "TABLETOP_DIP": "TRICEPS_EXTENSION",
    "TRICEPS_DIP": "TRICEPS_EXTENSION",
    "WEIGHTED_TRICEPS_DIP": "TRICEPS_EXTENSION",
    "TRICEPS_EXTENSION_ON_FLOOR": "TRICEPS_EXTENSION",
    "TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "WEIGHTED_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "TRICEPS_PUSHDOWN": "TRICEPS_EXTENSION",
    "SKULL_CRUSHER": "TRICEPS_EXTENSION",
    "CLOSE_GRIP_BENCH_PRESS": "TRICEPS_EXTENSION",
    "DIAMOND_PUSH_UP": "TRICEPS_EXTENSION",
    "TRICEPS_KICKBACK": "TRICEPS_EXTENSION",
    "OVERHEAD_TRICEPS_EXTENSION": "TRICEPS_EXTENSION",
    "DIP": "TRICEPS_EXTENSION",
    "WEIGHTED_DIP": "TRICEPS_EXTENSION",
    "JM_PRESS": "TRICEPS_EXTENSION",
    "TATE_PRESS": "TRICEPS_EXTENSION",
    # =========================================================================
    # PULL_UP Category
    # =========================================================================
    "BANDED_PULL_UP": "PULL_UP",
    "BURPEE_PULL_UP": "PULL_UP",
    "CHEST_TO_BAR_PULL_UP": "PULL_UP",
    "CHIN_UP": "PULL_UP",
    "CLOSE_GRIP_CHIN_UP": "PULL_UP",
    "CLOSE_GRIP_LAT_PULLDOWN": "PULL_UP",
    "CROSSOVER_CHIN_UP": "PULL_UP",
    "EZ_BAR_PULLOVER": "PULL_UP",
    "HANGING_HURDLE": "PULL_UP",
    "JUMPING_PULL_UPS": "PULL_UP",
    "KIPPING_PULL_UP": "PULL_UP",
    "KNEELING_LAT_PULLDOWN": "PULL_UP",
    "KNEELING_UNDERHAND_GRIP_LAT_PULLDOWN": "PULL_UP",
    "LAT_PULLDOWN": "PULL_UP",
    "L_PULL_UP": "PULL_UP",
    "MIXED_GRIP_CHIN_UP": "PULL_UP",
    "MIXED_GRIP_PULL_UP": "PULL_UP",
    "NEUTRAL_GRIP_CHIN_UP": "PULL_UP",
    "NEUTRAL_GRIP_PULL_UP": "PULL_UP",
    "ONE_ARM_CHIN_UP": "PULL_UP",
    "PARALLEL_CLOSE_GRIP_PULL_UP": "PULL_UP",
    "PULL_UP": "PULL_UP",
    "WEIGHTED_PULL_UP": "PULL_UP",
    "PULL_UPS": "PULL_UP",
    "REVERSE_CLOSE_GRIP_LAT_PULLDOWN": "PULL_UP",
    "STANDING_CABLE_PULLOVER": "PULL_UP",
    "STRAIGHT_ARM_PULLDOWN": "PULL_UP",
    "SUSPENDED_CHIN_UP": "PULL_UP",
    "SWISS_BALL_EZ_BAR_PULLOVER": "PULL_UP",
    "TOWEL_PULL_UP": "PULL_UP",
    "UNDERHAND_GRIP_LAT_PULLDOWN": "PULL_UP",
    "WEIGHTED_CHIN_UP": "PULL_UP",
    "WIDE_GRIP_LAT_PULLDOWN": "PULL_UP",
    "WIDE_GRIP_PULL_UP": "PULL_UP",
    "WIDE_GRIP_PULL_UPS": "PULL_UP",
    "COMMANDO_PULL_UP": "PULL_UP",
    "ARCHER_PULL_UP": "PULL_UP",
    "TYPEWRITER_PULL_UP": "PULL_UP",
    "MUSCLE_UP_PULL_UP": "PULL_UP",
    # =========================================================================
    # PUSH_UP Category
    # =========================================================================
    "ALTERNATING_STAGGERED_PUSH_UP": "PUSH_UP",
    "CHEST_PRESS_WITH_BAND": "PUSH_UP",
    "CLAPPING_PUSH_UP": "PUSH_UP",
    "CLOSE_GRIP_MEDICINE_BALL_PUSH_UP": "PUSH_UP",
    "CLOSE_HANDS_PUSH_UP": "PUSH_UP",
    "DECLINE_PUSH_UP": "PUSH_UP",
    "DIAMOND_PUSH_UP_ON_KNEES": "PUSH_UP",
    "DIVEBOMBER_PUSH_UP": "PUSH_UP",
    "EXPLOSIVE_CROSSOVER_PUSH_UP": "PUSH_UP",
    "EXPLOSIVE_PUSH_UP": "PUSH_UP",
    "FEET_ELEVATED_SIDE_TO_SIDE_PUSH_UP": "PUSH_UP",
    "FLOOR_PRESS": "PUSH_UP",
    "HAND_RELEASE_PUSH_UP": "PUSH_UP",
    "INCLINE_PUSH_UP": "PUSH_UP",
    "ISOMETRIC_EXPLOSIVE_PUSH_UP": "PUSH_UP",
    "JUDO_PUSH_UP": "PUSH_UP",
    "KNEELING_PUSH_UP": "PUSH_UP",
    "MEDICINE_BALL_CHEST_PASS": "PUSH_UP",
    "MEDICINE_BALL_PUSH_UP": "PUSH_UP",
    "MODIFIED_PUSH_UP": "PUSH_UP",
    "ONE_ARM_PUSH_UP": "PUSH_UP",
    "PARALLEL_BAR_DIP": "PUSH_UP",
    "PIKE_PUSH_UP": "PUSH_UP",
    "PLYOMETRIC_SIDE_TO_SIDE_PUSH_UP": "PUSH_UP",
    "PUSH_UP": "PUSH_UP",
    "WEIGHTED_PUSH_UP": "PUSH_UP",
    "PUSH_UP_AND_ROW": "PUSH_UP",
    "PUSH_UP_ON_SWISS_BALL": "PUSH_UP",
    "PUSH_UP_PLUS": "PUSH_UP",
    "PUSH_UP_WITH_FEET_ON_SWISS_BALL": "PUSH_UP",
    "PUSH_UP_WITH_HANDS_ON_SWISS_BALL": "PUSH_UP",
    "RING_PUSH_UP": "PUSH_UP",
    "SHOULDER_TAP_PUSH_UP": "PUSH_UP",
    "SINGLE_ARM_MEDICINE_BALL_PUSH_UP": "PUSH_UP",
    "SPIDERMAN_PUSH_UP": "PUSH_UP",
    "STACKED_FEET_PUSH_UP": "PUSH_UP",
    "STAGGERED_HANDS_PUSH_UP": "PUSH_UP",
    "STANDING_CABLE_CHEST_PRESS": "PUSH_UP",
    "STANDING_INCLINE_FLY": "PUSH_UP",
    "SUSPENDED_PUSH_UP": "PUSH_UP",
    "SWISS_BALL_PUSH_UP": "PUSH_UP",
    "SWISS_BALL_PUSH_UP_PLUS": "PUSH_UP",
    "T_PUSH_UP": "PUSH_UP",
    "TRIPLE_STOP_PUSH_UP": "PUSH_UP",
    "WIDE_HANDS_PUSH_UP": "PUSH_UP",
    "WALL_PUSH_UP": "PUSH_UP",
    "HINDU_PUSH_UP": "PUSH_UP",
    "ARCHER_PUSH_UP": "PUSH_UP",
    "PSEUDO_PLANCHE_PUSH_UP": "PUSH_UP",
    # =========================================================================
    # PLANK Category
    # =========================================================================
    "45_DEGREE_PLANK": "PLANK",
    "BEAR_CRAWL": "PLANK",
    "CROSS_BODY_MOUNTAIN_CLIMBER": "PLANK",
    "ELBOW_PLANK_PIKE_JACKS": "PLANK",
    "ELEVATED_FEET_PLANK": "PLANK",
    "ELEVATED_HANDS_PLANK": "PLANK",
    "ELEVATOR_ABS": "PLANK",
    "EXTENDED_PLANK": "PLANK",
    "FULL_PLANK_PASSE_TWIST": "PLANK",
    "INCHING_ELBOW_PLANK": "PLANK",
    "INCHWORM": "PLANK",
    "INCHWORM_TO_SIDE_PLANK": "PLANK",
    "KNEELING_PLANK": "PLANK",
    "KNEELING_SIDE_PLANK_WITH_LEG_LIFT": "PLANK",
    "LATERAL_ROLL": "PLANK",
    "LYING_REVERSE_PLANK": "PLANK",
    "MEDICINE_BALL_MOUNTAIN_CLIMBER": "PLANK",
    "MODIFIED_MOUNTAIN_CLIMBER_AND_EXTENSION": "PLANK",
    "MOUNTAIN_CLIMBER": "PLANK",
    "WEIGHTED_MOUNTAIN_CLIMBER": "PLANK",
    "MOUNTAIN_CLIMBER_ON_SLIDING_DISCS": "PLANK",
    "MOUNTAIN_CLIMBER_WITH_FEET_ON_BOSU_BALL": "PLANK",
    "MOUNTAIN_CLIMBER_WITH_HANDS_ON_BENCH": "PLANK",
    "MOUNTAIN_CLIMBER_WITH_HANDS_ON_SWISS_BALL": "PLANK",
    "ONE_ARM_ONE_LEG_PLANK": "PLANK",
    "ONE_LEG_PLANK": "PLANK",
    "PLANK": "PLANK",
    "WEIGHTED_PLANK": "PLANK",
    "PLANK_JACKS": "PLANK",
    "PLANK_KNEE_TWIST": "PLANK",
    "PLANK_ON_ELBOWS": "PLANK",
    "PLANK_PIKE_JUMPS": "PLANK",
    "PLANK_PIKES": "PLANK",
    "PLANK_TO_STAND_UP": "PLANK",
    "PLANK_WITH_ARM_RAISE": "PLANK",
    "PLANK_WITH_ARM_VARIATIONS": "PLANK",
    "PLANK_WITH_FEET_ON_SWISS_BALL": "PLANK",
    "PLANK_WITH_GLUTE_KICK_BACK": "PLANK",
    "PLANK_WITH_HIP_EXTENSION": "PLANK",
    "PLANK_WITH_KNEE_TO_CHEST": "PLANK",
    "PLANK_WITH_KNEE_TO_ELBOW": "PLANK",
    "PLANK_WITH_LEG_LIFT": "PLANK",
    "PLANK_WITH_OBLIQUE_CRUNCH": "PLANK",
    "PLYOMETRIC_SIDE_PLANK": "PLANK",
    "REVERSE_PLANK": "PLANK",
    "ROLLING_SIDE_PLANK": "PLANK",
    "SIDE_KICK_PLANK": "PLANK",
    "SIDE_PLANK": "PLANK",
    "WEIGHTED_SIDE_PLANK": "PLANK",
    "SIDE_PLANK_AND_ROW": "PLANK",
    "SIDE_PLANK_LEG_LIFT": "PLANK",
    "SIDE_PLANK_WITH_ELBOW_ON_BOSU_BALL": "PLANK",
    "SIDE_PLANK_WITH_FEET_ON_BENCH": "PLANK",
    "SIDE_PLANK_WITH_HIP_ABDUCTION": "PLANK",
    "SIDE_PLANK_WITH_KNEE_CIRCLE": "PLANK",
    "SIDE_PLANK_WITH_KNEE_TUCK": "PLANK",
    "SIDE_PLANK_WITH_LEG_LIFT": "PLANK",
    "SIDE_PLANK_WITH_REACH_UNDER": "PLANK",
    "SINGLE_ARM_PLANK": "PLANK",
    "SINGLE_LEG_ELEVATED_FEET_PLANK": "PLANK",
    "SINGLE_LEG_FLEX_AND_EXTEND": "PLANK",
    "SINGLE_LEG_SIDE_PLANK": "PLANK",
    "SLIDING_MOUNTAIN_CLIMBER": "PLANK",
    "STRAIGHT_ARM_PLANK": "PLANK",
    "STRAIGHT_ARM_PLANK_WITH_SHOULDER_TOUCH": "PLANK",
    "SUPERMAN_PLANK": "PLANK",
    "SWISS_BALL_PLANK": "PLANK",
    "SWISS_BALL_PLANK_LEG_LIFT": "PLANK",
    "SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD": "PLANK",
    "SWISS_BALL_PLANK_WITH_FEET_ON_BENCH": "PLANK",
    "SWISS_BALL_PRONE_JACKKNIFE": "PLANK",
    "SWISS_BALL_SIDE_PLANK": "PLANK",
    "THREE_WAY_PLANK": "PLANK",
    "TOWEL_PLANK_AND_KNEE_IN": "PLANK",
    "T_STABILIZATION": "PLANK",
    "TURKISH_GET_UP_TO_SIDE_PLANK": "PLANK",
    "TWO_POINT_PLANK": "PLANK",
    "WEIGHTED_EXTENDED_PLANK": "PLANK",
    "WEIGHTED_PLANK_ON_ELBOWS": "PLANK",
    "WIDE_STANCE_PLANK_WITH_DIAGONAL_ARM_LIFT": "PLANK",
    "WIDE_STANCE_PLANK_WITH_DIAGONAL_LEG_LIFT": "PLANK",
    "WIDE_STANCE_PLANK_WITH_LEG_LIFT": "PLANK",
    "WIDE_STANCE_PLANK_WITH_OPPOSITE_ARM_AND_LEG_LIFT": "PLANK",
    "FOREARM_PLANK": "PLANK",
    "HIGH_PLANK": "PLANK",
    "LOW_PLANK": "PLANK",
    "UP_DOWN_PLANK": "PLANK",
    "BODY_SAW": "PLANK",
    # =========================================================================
    # CORE Category
    # =========================================================================
    "BICYCLE_MANEUVER": "CORE",
    "CABLE_CORE_PRESS": "CORE",
    "DEAD_BUG": "CORE",
    "FIRE_HYDRANT": "CORE",
    "HALF_KNEEL_CHOP": "CORE",
    "HALF_KNEEL_LIFT": "CORE",
    "HALF_KNEEL_ROTATION": "CORE",
    "HANGING_KNEE_RAISE": "CORE",
    "MEDICINE_BALL_SLAM": "CORE",
    "OVERHEAD_CIRCLES": "CORE",
    "PRONE_BACK_EXTENSION": "CORE",
    "RUSSIAN_TWIST": "CORE",
    "SLAM_BALL": "CORE",
    "SPIDERMAN_CRUNCH": "CORE",
    "STANDING_ROTATIONAL_CHOP": "CORE",
    "STANDING_ROTATIONAL_LIFT": "CORE",
    "SUPERMAN": "CORE",
    "SUPERMAN_HOLD": "CORE",
    "SWISS_BALL_BACK_EXTENSION": "CORE",
    "SWISS_BALL_CRUNCH": "CORE",
    "SWISS_BALL_DECLINE_OBLIQUE_CRUNCH": "CORE",
    "SWISS_BALL_JACKKNIFE": "CORE",
    "SWISS_BALL_PIKE": "CORE",
    "SWISS_BALL_PLANK_LEG_LIFT_AND_HOLD_CORE": "CORE",
    "SWISS_BALL_ROLLOUT": "CORE",
    "SWISS_BALL_STIR_THE_POT": "CORE",
    "SWISS_BALL_V_UP": "CORE",
    "TUCK_HOLD": "CORE",
    "V_UP": "CORE",
    "WEIGHTED_RUSSIAN_TWIST": "CORE",
    "WEIGHTED_V_UP": "CORE",
    "WINDMILL": "CORE",
    "WINDSHIELD_WIPER": "CORE",
    "AB_WHEEL_ROLLOUT": "CORE",
    "HOLLOW_BODY_HOLD": "CORE",
    "HOLLOW_ROCK": "CORE",
    "BIRD_DOG": "CORE",
    "PALLOF_PRESS": "CORE",
    "LANDMINE_ROTATION": "CORE",
    "CABLE_WOODCHOP": "CORE",
    "FARMERS_WALK": "CORE",
    "SUITCASE_CARRY": "CORE",
    "TURKISH_GET_UP": "CORE",
    "BICYCLE_CRUNCH": "CORE",
    # =========================================================================
    # CRUNCH Category
    # =========================================================================
    "BICYCLE_CRUNCH_EXERCISE": "CRUNCH",
    "CABLE_CRUNCH": "CRUNCH",
    "CIRCULAR_ARM_CRUNCH": "CRUNCH",
    "CROSSED_ARMS_CRUNCH": "CRUNCH",
    "CROSSOVER_CRUNCH": "CRUNCH",
    "CRUNCH": "CRUNCH",
    "WEIGHTED_CRUNCH": "CRUNCH",
    "CRUNCH_CHOP": "CRUNCH",
    "DOUBLE_CRUNCH": "CRUNCH",
    "DUMBBELL_LEG_EXTENSION_HIP_LIFT": "CRUNCH",
    "ELBOW_TO_KNEE_CRUNCH": "CRUNCH",
    "FLUTTER_KICK": "CRUNCH",
    "FOAM_ROLLER_REVERSE_CRUNCH_ON_BENCH": "CRUNCH",
    "FOAM_ROLLER_REVERSE_CRUNCH_WITH_DUMBBELL": "CRUNCH",
    "FOAM_ROLLER_REVERSE_CRUNCH_WITH_MEDICINE_BALL": "CRUNCH",
    "FROG_PRESS": "CRUNCH",
    "HANGING_KNEE_RAISE_OBLIQUE_CRUNCH": "CRUNCH",
    "HIP_CROSSOVER": "CRUNCH",
    "HOLLOW_ROCK_CRUNCH": "CRUNCH",
    "INCLINE_REVERSE_CRUNCH": "CRUNCH",
    "KNEELING_CABLE_CRUNCH": "CRUNCH",
    "KNEELING_CROSS_CRUNCH": "CRUNCH",
    "KNEELING_OBLIQUE_CABLE_CRUNCH": "CRUNCH",
    "KNEES_TO_ELBOW": "CRUNCH",
    "LEG_EXTENSIONS": "CRUNCH",
    "LEG_LEVERS": "CRUNCH",
    "MCGILL_CURL_UP": "CRUNCH",
    "MODIFIED_PILATES_ROLL_UP_WITH_BALL": "CRUNCH",
    "PILATES_CRUNCH": "CRUNCH",
    "PILATES_ROLL_UP_WITH_BALL": "CRUNCH",
    "RAISED_LEGS_CRUNCH": "CRUNCH",
    "REVERSE_CRUNCH": "CRUNCH",
    "WEIGHTED_REVERSE_CRUNCH": "CRUNCH",
    "REVERSE_CRUNCH_ON_A_BENCH": "CRUNCH",
    "REVERSE_CURL_AND_LIFT": "CRUNCH",
    "ROTATIONAL_LIFT": "CRUNCH",
    "SEATED_ALTERNATING_REVERSE_CRUNCH": "CRUNCH",
    "SEATED_LEG_U": "CRUNCH",
    "SIDE_TO_SIDE_CRUNCH_AND_WEAVE": "CRUNCH",
    "SINGLE_LEG_REVERSE_CRUNCH": "CRUNCH",
    "SKATER_CRUNCH_CROSS": "CRUNCH",
    "STANDING_CABLE_CRUNCH": "CRUNCH",
    "STANDING_SIDE_CRUNCH": "CRUNCH",
    "STEP_CLIMB": "CRUNCH",
    "STRAIGHT_LEG_CRUNCH": "CRUNCH",
    "SWISS_BALL_CRUNCH_EXERCISE": "CRUNCH",
    "SWISS_BALL_REVERSE_CRUNCH": "CRUNCH",
    "SWISS_BALL_SIDE_CRUNCH": "CRUNCH",
    "THORACIC_CRUNCHES_ON_FOAM_ROLLER": "CRUNCH",
    "TOES_TO_BAR": "CRUNCH",
    "TRICEPS_CRUNCH": "CRUNCH",
    "WEIGHTED_CROSSOVER_CRUNCH": "CRUNCH",
    "WEIGHTED_DOUBLE_CRUNCH": "CRUNCH",
    "OBLIQUE_CRUNCH": "CRUNCH",
    "VERTICAL_LEG_CRUNCH": "CRUNCH",
    "LONG_ARM_CRUNCH": "CRUNCH",
    "DEAD_BUG_CRUNCH": "CRUNCH",
    # =========================================================================
    # SIT_UP Category
    # =========================================================================
    "ALTERNATING_SIT_UP": "SIT_UP",
    "BENT_KNEE_V_UP": "SIT_UP",
    "BUTTERFLY_SIT_UP": "SIT_UP",
    "CROSS_PUNCH_ROLL_UP": "SIT_UP",
    "CROSSED_ARMS_SIT_UP": "SIT_UP",
    "GET_UP_SIT_UP": "SIT_UP",
    "HOVERING_SIT_UP": "SIT_UP",
    "KETTLEBELL_SIT_UP": "SIT_UP",
    "MEDICINE_BALL_ALTERNATING_V_UP": "SIT_UP",
    "MEDICINE_BALL_SIT_UP": "SIT_UP",
    "MEDICINE_BALL_V_UP": "SIT_UP",
    "MODIFIED_SIT_UP": "SIT_UP",
    "NEGATIVE_SIT_UP": "SIT_UP",
    "ONE_ARM_FULL_SIT_UP": "SIT_UP",
    "RECLINING_CIRCLE": "SIT_UP",
    "REVERSE_CURL_UP": "SIT_UP",
    "ROLLING_LIKE_BALL_PULLOVER": "SIT_UP",
    "SINGLE_LEG_SWISS_BALL_JACKKNIFE": "SIT_UP",
    "SIT_UP": "SIT_UP",
    "WEIGHTED_SIT_UP": "SIT_UP",
    "SLOW_BICYCLE": "SIT_UP",
    "THE_CLIMB": "SIT_UP",
    "V_UP_SIT_UP": "SIT_UP",
    "WEIGHTED_BENT_KNEE_V_UP": "SIT_UP",
    "WEIGHTED_BUTTERFLY_SIT_UP": "SIT_UP",
    "WEIGHTED_MEDICINE_BALL_SIT_UP": "SIT_UP",
    "WEIGHTED_MEDICINE_BALL_V_UP": "SIT_UP",
    "WEIGHTED_RECLINING_CIRCLE": "SIT_UP",
    "WEIGHTED_V_UP_SIT_UP": "SIT_UP",
    "X_ABS": "SIT_UP",
    "GHD_SIT_UP": "SIT_UP",
    "ANCHORED_SIT_UP": "SIT_UP",
    "DECLINE_SIT_UP": "SIT_UP",
    # =========================================================================
    # LEG_RAISE Category
    # =========================================================================
    "CAPTAIN_CHAIR_LEG_RAISE": "LEG_RAISE",
    "FLAT_BENCH_HIP_LIFT": "LEG_RAISE",
    "HANGING_LEG_RAISE": "LEG_RAISE",
    "WEIGHTED_HANGING_LEG_RAISE": "LEG_RAISE",
    "HIP_LIFT": "LEG_RAISE",
    "HIP_LIFT_WITH_LEG_RAISE": "LEG_RAISE",
    "KNEE_HIP_RAISE": "LEG_RAISE",
    "LEG_RAISE": "LEG_RAISE",
    "WEIGHTED_LEG_RAISE": "LEG_RAISE",
    "LEG_RAISE_ON_FOAM_ROLLER": "LEG_RAISE",
    "LYING_CABLE_HIP_RAISE": "LEG_RAISE",
    "LYING_KNEE_RAISE": "LEG_RAISE",
    "LYING_LEG_RAISE": "LEG_RAISE",
    "LYING_LEG_RAISE_TO_HIP_LIFT": "LEG_RAISE",
    "LYING_LEG_RAISE_TO_HIP_RAISE": "LEG_RAISE",
    "PARALLEL_BAR_KNEE_RAISE": "LEG_RAISE",
    "PARALLEL_BAR_LEG_RAISE": "LEG_RAISE",
    "REVERSE_HIP_LIFT": "LEG_RAISE",
    "REVERSE_HIP_RAISE": "LEG_RAISE",
    "SEATED_HIP_RAISE": "LEG_RAISE",
    "SINGLE_LEG_HIP_RAISE": "LEG_RAISE",
    "STEP_THROUGH": "LEG_RAISE",
    "STRAIGHT_LEG_HIP_RAISE": "LEG_RAISE",
    "SUSPENDED_KNEE_RAISE": "LEG_RAISE",
    "SWISS_BALL_LEG_RAISE": "LEG_RAISE",
    "SWISS_BALL_REVERSE_HIP_RAISE": "LEG_RAISE",
    "V_RAISE": "LEG_RAISE",
    "WINDSHIELD_WIPER_LEG_RAISE": "LEG_RAISE",
    "FLUTTER_KICKS": "LEG_RAISE",
    "SCISSOR_KICKS": "LEG_RAISE",
    "HANGING_STRAIGHT_LEG_RAISE": "LEG_RAISE",
    "LYING_SIDE_LEG_RAISE": "LEG_RAISE",
    # =========================================================================
    # LEG_CURL Category (Hamstrings)
    # =========================================================================
    "BALL_DIG": "LEG_CURL",
    "BAND_GOOD_MORNING": "LEG_CURL",
    "BARBELL_GOOD_MORNING": "LEG_CURL",
    "BARBELL_STRAIGHT_LEG_GOOD_MORNING": "LEG_CURL",
    "GOOD_MORNING": "LEG_CURL",
    "WEIGHTED_GOOD_MORNING": "LEG_CURL",
    "LEG_CURL": "LEG_CURL",
    "WEIGHTED_LEG_CURL": "LEG_CURL",
    "LYING_LEG_CURL": "LEG_CURL",
    "LYING_LEG_CURL_EXERCISE": "LEG_CURL",
    "NORDIC_HAMSTRING_CURL": "LEG_CURL",
    "SEATED_BARBELL_GOOD_MORNING": "LEG_CURL",
    "SEATED_LEG_CURL": "LEG_CURL",
    "SINGLE_LEG_BARBELL_GOOD_MORNING": "LEG_CURL",
    "SINGLE_LEG_SLIDING_LEG_CURL": "LEG_CURL",
    "SLIDING_LEG_CURL": "LEG_CURL",
    "SPLIT_BARBELL_GOOD_MORNING": "LEG_CURL",
    "SPLIT_STANCE_EXTENSION": "LEG_CURL",
    "STANDING_LEG_CURL": "LEG_CURL",
    "STAGGERED_STANCE_GOOD_MORNING": "LEG_CURL",
    "SWISS_BALL_HIP_RAISE_AND_LEG_CURL": "LEG_CURL",
    "ZERCHER_GOOD_MORNING": "LEG_CURL",
    "HAMSTRING_CURL": "LEG_CURL",
    "PRONE_LEG_CURL": "LEG_CURL",
    "GLUTE_HAM_RAISE": "LEG_CURL",
    # =========================================================================
    # CALF_RAISE Category
    # =========================================================================
    "BARBELL_CALF_RAISE": "CALF_RAISE",
    "CALF_PRESS_ON_LEG_PRESS": "CALF_RAISE",
    "CALF_RAISE": "CALF_RAISE",
    "WEIGHTED_CALF_RAISE": "CALF_RAISE",
    "DONKEY_CALF_RAISE": "CALF_RAISE",
    "DUMBBELL_CALF_RAISE": "CALF_RAISE",
    "DUMBBELL_SEATED_CALF_RAISE": "CALF_RAISE",
    "DUMBBELL_SINGLE_LEG_CALF_RAISE": "CALF_RAISE",
    "LEG_PRESS_CALF_RAISE": "CALF_RAISE",
    "SEATED_CALF_RAISE": "CALF_RAISE",
    "WEIGHTED_SEATED_CALF_RAISE": "CALF_RAISE",
    "SEATED_DUMBBELL_TOE_RAISE": "CALF_RAISE",
    "SINGLE_LEG_BENT_KNEE_CALF_RAISE": "CALF_RAISE",
    "SINGLE_LEG_CALF_RAISE": "CALF_RAISE",
    "SINGLE_LEG_DECLINE_PUSH_UP": "CALF_RAISE",
    "SINGLE_LEG_DONKEY_CALF_RAISE": "CALF_RAISE",
    "SINGLE_LEG_HIP_RAISE_WITH_KNEE_HOLD": "CALF_RAISE",
    "SINGLE_LEG_STANDING_CALF_RAISE": "CALF_RAISE",
    "SMITH_MACHINE_CALF_RAISE": "CALF_RAISE",
    "STANDING_CALF_RAISE": "CALF_RAISE",
    "WEIGHTED_STANDING_CALF_RAISE": "CALF_RAISE",
    "STANDING_DUMBBELL_CALF_RAISE": "CALF_RAISE",
    "TIBIALIS_RAISE": "CALF_RAISE",
    # =========================================================================
    # HIP_RAISE Category (Glutes)
    # =========================================================================
    "BARBELL_HIP_THRUST": "HIP_RAISE",
    "BARBELL_HIP_THRUST_ON_FLOOR": "HIP_RAISE",
    "BARBELL_HIP_THRUST_WITH_BENCH": "HIP_RAISE",
    "BENT_KNEE_SWISS_BALL_REVERSE_HIP_RAISE": "HIP_RAISE",
    "BANDED_GLUTE_BRIDGE": "HIP_RAISE",
    "BODY_WEIGHT_GLUTE_BRIDGE": "HIP_RAISE",
    "BRIDGE": "HIP_RAISE",
    "WEIGHTED_BRIDGE": "HIP_RAISE",
    "DUMBBELL_SINGLE_LEG_GLUTE_BRIDGE": "HIP_RAISE",
    "ELEVATED_SINGLE_LEG_HIP_THRUST": "HIP_RAISE",
    "FLOOR_GLUTE_HAM_RAISE": "HIP_RAISE",
    "GLUTE_BRIDGE": "HIP_RAISE",
    "WEIGHTED_GLUTE_BRIDGE": "HIP_RAISE",
    "GLUTE_BRIDGE_HOLD": "HIP_RAISE",
    "GLUTE_BRIDGE_MARCH": "HIP_RAISE",
    "GLUTE_BRIDGE_ON_BENCH": "HIP_RAISE",
    "GLUTE_BRIDGE_WITH_LEG_LIFT": "HIP_RAISE",
    "HIP_RAISE": "HIP_RAISE",
    "WEIGHTED_HIP_RAISE": "HIP_RAISE",
    "HIP_RAISE_WITH_FEET_ON_SWISS_BALL": "HIP_RAISE",
    "HIP_RAISE_WITH_HEAD_ON_SWISS_BALL": "HIP_RAISE",
    "HIP_RAISE_WITH_KNEES_SQUEEZED": "HIP_RAISE",
    "HIP_THRUST": "HIP_RAISE",
    "WEIGHTED_HIP_THRUST": "HIP_RAISE",
    "HIP_THRUST_AND_LEG_RAISE": "HIP_RAISE",
    "INCLINE_REAR_LEG_EXTENSION": "HIP_RAISE",
    "KETTLEBELL_SWING": "HIP_RAISE",
    "MARCHING_HIP_RAISE": "HIP_RAISE",
    "WEIGHTED_MARCHING_HIP_RAISE": "HIP_RAISE",
    "MARCHING_HIP_RAISE_WITH_FEET_ON_A_SWISS_BALL": "HIP_RAISE",
    "SINGLE_LEG_ELEVATED_FEET_HIP_RAISE": "HIP_RAISE",
    "SINGLE_LEG_GLUTE_BRIDGE": "HIP_RAISE",
    "SINGLE_LEG_HIP_THRUST": "HIP_RAISE",
    "SINGLE_LEG_SWISS_BALL_HIP_RAISE_AND_LEG_CURL": "HIP_RAISE",
    "SWISS_BALL_HIP_RAISE": "HIP_RAISE",
    "FROG_PUMP": "HIP_RAISE",
    "CABLE_PULL_THROUGH": "HIP_RAISE",
    # =========================================================================
    # HIP_STABILITY Category
    # =========================================================================
    "BAND_SIDE_LYING_LEG_RAISE": "HIP_STABILITY",
    "CLAMSHELL": "HIP_STABILITY",
    "DEAD_BUG_HIP_STABILITY": "HIP_STABILITY",
    "EXTERNAL_HIP_RAISE": "HIP_STABILITY",
    "HIP_CIRCLES": "HIP_STABILITY",
    "HIP_STABILITY": "HIP_STABILITY",
    "WEIGHTED_HIP_STABILITY": "HIP_STABILITY",
    "INNER_THIGH_LIFT": "HIP_STABILITY",
    "LATERAL_WALKS_WITH_BAND_AT_ANKLES": "HIP_STABILITY",
    "LYING_HIP_ABDUCTION": "HIP_STABILITY",
    "LYING_SIDE_LEG_RAISE_HIP_STABILITY": "HIP_STABILITY",
    "PRETZEL_SIDE_KICK": "HIP_STABILITY",
    "PRONE_HIP_INTERNAL_ROTATION": "HIP_STABILITY",
    "QUADRUPED": "HIP_STABILITY",
    "QUADRUPED_HIP_EXTENSION": "HIP_STABILITY",
    "QUADRUPED_WITH_LEG_LIFT": "HIP_STABILITY",
    "SIDE_LYING_LEG_RAISE": "HIP_STABILITY",
    "STANDING_HIP_ABDUCTION": "HIP_STABILITY",
    "SUPINE_HIP_INTERNAL_ROTATION": "HIP_STABILITY",
    "BANDED_CLAMSHELL": "HIP_STABILITY",
    "BANDED_LATERAL_WALK": "HIP_STABILITY",
    "BANDED_MONSTER_WALK": "HIP_STABILITY",
    "CABLE_HIP_ABDUCTION": "HIP_STABILITY",
    "CABLE_HIP_ADDUCTION": "HIP_STABILITY",
    "HIP_ABDUCTION_MACHINE": "HIP_STABILITY",
    "HIP_ADDUCTION_MACHINE": "HIP_STABILITY",
    # =========================================================================
    # FLYE Category
    # =========================================================================
    "CABLE_CROSSOVER": "FLYE",
    "CABLE_FLY": "FLYE",
    "DECLINE_DUMBBELL_FLYE": "FLYE",
    "DUMBBELL_FLYE": "FLYE",
    "FLYE": "FLYE",
    "WEIGHTED_FLYE": "FLYE",
    "INCLINE_DUMBBELL_FLYE": "FLYE",
    "INCLINE_REVERSE_FLY": "FLYE",
    "KETTLEBELL_FLYE": "FLYE",
    "KNEELING_REAR_FLY": "FLYE",
    "MACHINE_FLY": "FLYE",
    "PEC_DECK": "FLYE",
    "REVERSE_FLY": "FLYE",
    "SINGLE_ARM_STANDING_CABLE_REVERSE_FLY": "FLYE",
    "SWISS_BALL_DUMBBELL_FLYE": "FLYE",
    "CHEST_FLY": "FLYE",
    "CABLE_CHEST_FLY": "FLYE",
    "HIGH_CABLE_FLY": "FLYE",
    "LOW_CABLE_FLY": "FLYE",
    # =========================================================================
    # SHRUG Category
    # =========================================================================
    "BARBELL_JUMP_SHRUG": "SHRUG",
    "BARBELL_SHRUG": "SHRUG",
    "BARBELL_UPRIGHT_ROW": "SHRUG",
    "BEHIND_THE_BACK_BARBELL_SHRUG": "SHRUG",
    "BEHIND_THE_BACK_SMITH_MACHINE_SHRUG": "SHRUG",
    "CABLE_SHRUG": "SHRUG",
    "DUMBBELL_JUMP_SHRUG": "SHRUG",
    "DUMBBELL_SHRUG": "SHRUG",
    "DUMBBELL_UPRIGHT_ROW": "SHRUG",
    "INCLINE_DUMBBELL_SHRUG": "SHRUG",
    "OVERHEAD_BARBELL_SHRUG": "SHRUG",
    "OVERHEAD_DUMBBELL_SHRUG": "SHRUG",
    "SCAPTION_AND_SHRUG_SHRUG": "SHRUG",
    "SCAPULAR_RETRACTION": "SHRUG",
    "SERRATUS_CHAIR_SHRUG": "SHRUG",
    "SERRATUS_SHRUG": "SHRUG",
    "SHRUG": "SHRUG",
    "WEIGHTED_SHRUG": "SHRUG",
    "WIDE_GRIP_JUMP_SHRUG": "SHRUG",
    "TRAP_BAR_SHRUG": "SHRUG",
    # =========================================================================
    # HYPEREXTENSION Category (Back Extension)
    # =========================================================================
    "BACK_EXTENSION_WITH_OPPOSITE_ARM_AND_LEG_REACH": "HYPEREXTENSION",
    "BASE_ROTATIONS": "HYPEREXTENSION",
    "BENT_KNEE_REVERSE_HYPEREXTENSION": "HYPEREXTENSION",
    "DOUBLE_LEG_HIP_EXTENSION_AND_CROSS": "HYPEREXTENSION",
    "GLUTE_FOCUSED_BACK_EXTENSION": "HYPEREXTENSION",
    "HYPEREXTENSION": "HYPEREXTENSION",
    "WEIGHTED_HYPEREXTENSION": "HYPEREXTENSION",
    "PRONE_COBRA": "HYPEREXTENSION",
    "PRONE_FLUTTER_KICKS": "HYPEREXTENSION",
    "REVERSE_HYPEREXTENSION": "HYPEREXTENSION",
    "WEIGHTED_REVERSE_HYPEREXTENSION": "HYPEREXTENSION",
    "SUPERMAN_FROM_FLOOR": "HYPEREXTENSION",
    "SWISS_BALL_BACK_EXTENSION_WITH_ROTATION": "HYPEREXTENSION",
    "SWISS_BALL_HYPEREXTENSION": "HYPEREXTENSION",
    "SWISS_BALL_OPPOSITE_ARM_AND_LEG_LIFT": "HYPEREXTENSION",
    "BACK_EXTENSION": "HYPEREXTENSION",
    "WEIGHTED_BACK_EXTENSION": "HYPEREXTENSION",
    "ROMAN_CHAIR_BACK_EXTENSION": "HYPEREXTENSION",
    "GHD_BACK_EXTENSION": "HYPEREXTENSION",
    # =========================================================================
    # OLYMPIC_LIFT Category
    # =========================================================================
    "ALTERNATING_HANG_PULL": "OLYMPIC_LIFT",
    "ALTERNATING_SINGLE_ARM_HANG_CLEAN": "OLYMPIC_LIFT",
    "BARBELL_CLEAN_AND_JERK": "OLYMPIC_LIFT",
    "BARBELL_HANG_CLEAN": "OLYMPIC_LIFT",
    "BARBELL_HANG_PULL": "OLYMPIC_LIFT",
    "BARBELL_HANG_SNATCH": "OLYMPIC_LIFT",
    "BARBELL_HIGH_PULL": "OLYMPIC_LIFT",
    "BARBELL_MUSCLE_SNATCH": "OLYMPIC_LIFT",
    "BARBELL_POWER_CLEAN": "OLYMPIC_LIFT",
    "BARBELL_POWER_SNATCH": "OLYMPIC_LIFT",
    "BARBELL_SNATCH": "OLYMPIC_LIFT",
    "BARBELL_SPLIT_JERK": "OLYMPIC_LIFT",
    "CLEAN": "OLYMPIC_LIFT",
    "CLEAN_AND_JERK": "OLYMPIC_LIFT",
    "CLEAN_AND_PRESS": "OLYMPIC_LIFT",
    "DUMBBELL_CLEAN": "OLYMPIC_LIFT",
    "DUMBBELL_CLEAN_AND_JERK": "OLYMPIC_LIFT",
    "DUMBBELL_HANG_CLEAN": "OLYMPIC_LIFT",
    "DUMBBELL_HANG_PULL": "OLYMPIC_LIFT",
    "DUMBBELL_HANG_SNATCH": "OLYMPIC_LIFT",
    "DUMBBELL_HIGH_PULL": "OLYMPIC_LIFT",
    "DUMBBELL_POWER_CLEAN": "OLYMPIC_LIFT",
    "DUMBBELL_SNATCH": "OLYMPIC_LIFT",
    "DUMBBELL_SPLIT_ALTERNATE_FOOT_SNATCH": "OLYMPIC_LIFT",
    "DUMBBELL_SPLIT_JERK": "OLYMPIC_LIFT",
    "HANG_CLEAN": "OLYMPIC_LIFT",
    "HANG_PULL": "OLYMPIC_LIFT",
    "HANG_SNATCH": "OLYMPIC_LIFT",
    "HIGH_PULL": "OLYMPIC_LIFT",
    "KETTLEBELL_HANG_PULL": "OLYMPIC_LIFT",
    "KETTLEBELL_SNATCH": "OLYMPIC_LIFT",
    "KETTLEBELL_SWING_SNATCH": "OLYMPIC_LIFT",
    "MED_BALL_CLEAN": "OLYMPIC_LIFT",
    "MUSCLE_CLEAN": "OLYMPIC_LIFT",
    "MUSCLE_SNATCH": "OLYMPIC_LIFT",
    "ONE_HAND_DUMBBELL_SPLIT_SNATCH": "OLYMPIC_LIFT",
    "OVERHEAD_SQUAT_TO_SPLIT_SNATCH": "OLYMPIC_LIFT",
    "POWER_CLEAN": "OLYMPIC_LIFT",
    "POWER_JERK": "OLYMPIC_LIFT",
    "POWER_SNATCH": "OLYMPIC_LIFT",
    "SINGLE_ARM_DUMBBELL_SNATCH": "OLYMPIC_LIFT",
    "SINGLE_ARM_HANG_SNATCH": "OLYMPIC_LIFT",
    "SINGLE_ARM_KETTLEBELL_SNATCH": "OLYMPIC_LIFT",
    "SNATCH": "OLYMPIC_LIFT",
    "SPLIT_JERK": "OLYMPIC_LIFT",
    "SQUAT_CLEAN": "OLYMPIC_LIFT",
    "SQUAT_SNATCH": "OLYMPIC_LIFT",
    "THRUSTER": "OLYMPIC_LIFT",
    "JERK": "OLYMPIC_LIFT",
    "PUSH_JERK": "OLYMPIC_LIFT",
    "CLUSTER": "OLYMPIC_LIFT",
    # =========================================================================
    # PLYO Category (Plyometrics)
    # =========================================================================
    "ALTERNATING_JUMP_LUNGE": "PLYO",
    "BARBELL_JUMP_SQUAT": "PLYO",
    "BOUNDING": "PLYO",
    "BOX_JUMP": "PLYO",
    "WEIGHTED_BOX_JUMP": "PLYO",
    "BOX_JUMP_OVERS": "PLYO",
    "BROAD_JUMP": "PLYO",
    "BURPEE": "PLYO",
    "BURPEE_BOX_JUMP": "PLYO",
    "BURPEE_BOX_JUMP_OVER": "PLYO",
    "BURPEE_OVER_BAR": "PLYO",
    "DEPTH_JUMP": "PLYO",
    "DUMBBELL_JUMP_SQUAT": "PLYO",
    "DUMBBELL_SPLIT_JUMP": "PLYO",
    "FRONT_KNEE_STRIKE": "PLYO",
    "HIGH_BOX_JUMP": "PLYO",
    "ISOMETRIC_EXPLOSIVE_BODY_WEIGHT_JUMP_SQUAT": "PLYO",
    "JUMP_SQUAT": "PLYO",
    "WEIGHTED_JUMP_SQUAT": "PLYO",
    "KNEE_TUCK_JUMP": "PLYO",
    "LATERAL_BOX_JUMP": "PLYO",
    "LATERAL_JUMP": "PLYO",
    "WEIGHTED_LATERAL_JUMP": "PLYO",
    "LATERAL_LEAP_AND_HOP": "PLYO",
    "LATERAL_PLYO_SQUATS": "PLYO",
    "LATERAL_SLIDE": "PLYO",
    "LONG_JUMP": "PLYO",
    "MEDICINE_BALL_SLAM_PLYO": "PLYO",
    "PLYOMETRIC_PUSH_UP": "PLYO",
    "POWER_DROP": "PLYO",
    "PUSH_UP_JACK": "PLYO",
    "SINGLE_ARM_MED_BALL_SLAM": "PLYO",
    "SINGLE_LEG_BOX_JUMP": "PLYO",
    "SINGLE_LEG_DEPTH_JUMP": "PLYO",
    "SINGLE_LEG_JUMP": "PLYO",
    "SINGLE_LEG_LATERAL_HOP": "PLYO",
    "SINGLE_LEG_LATERAL_TO_MEDIAL_HOP": "PLYO",
    "SINGLE_LEG_TRIPLE_HOP": "PLYO",
    "SKATER_JUMP": "PLYO",
    "SQUAT_JUMP": "PLYO",
    "SQUAT_JUMP_TO_BOX": "PLYO",
    "STANDING_BROAD_JUMP": "PLYO",
    "STANDING_LONG_JUMP": "PLYO",
    "TRIPLE_JUMP": "PLYO",
    "TUCK_JUMP": "PLYO",
    "WEIGHTED_TUCK_JUMP": "PLYO",
    "VERTICAL_JUMP": "PLYO",
    "PLYO_PUSH_UP": "PLYO",
    "STAR_JUMP": "PLYO",
    "SPLIT_JUMP": "PLYO",
    "POGO_HOP": "PLYO",
    "ANKLE_HOP": "PLYO",
    # =========================================================================
    # CHOP Category
    # =========================================================================
    "CABLE_PULL_THROUGH_CHOP": "CHOP",
    "CABLE_ROTATIONAL_LIFT": "CHOP",
    "CABLE_WOODCHOP_CHOP": "CHOP",
    "CHOP": "CHOP",
    "WEIGHTED_CHOP": "CHOP",
    "CROSS_CHOP_TO_KNEE": "CHOP",
    "DUMBBELL_CHOP": "CHOP",
    "HALF_KNEELING_ROTATION": "CHOP",
    "HALF_KNEELING_ROTATIONAL_CHOP": "CHOP",
    "HALF_KNEELING_ROTATIONAL_REVERSE_CHOP": "CHOP",
    "HALF_KNEELING_STABILITY_CHOP": "CHOP",
    "HALF_KNEELING_STABILITY_REVERSE_CHOP": "CHOP",
    "KNEELING_ROTATIONAL_CHOP": "CHOP",
    "KNEELING_ROTATIONAL_REVERSE_CHOP": "CHOP",
    "KNEELING_STABILITY_CHOP": "CHOP",
    "KNEELING_WOODCHOPPER": "CHOP",
    "MEDICINE_BALL_WOODCHOPS": "CHOP",
    "POWER_SQUAT_CHOPS": "CHOP",
    "STANDING_ROTATIONAL_CHOP_CHOP": "CHOP",
    "STANDING_SPLIT_ROTATIONAL_CHOP": "CHOP",
    "STANDING_SPLIT_ROTATIONAL_REVERSE_CHOP": "CHOP",
    "STANDING_STABILITY_REVERSE_CHOP": "CHOP",
    "WOOD_CHOP": "CHOP",
    "WEIGHTED_WOOD_CHOP": "CHOP",
    # =========================================================================
    # CARRY Category
    # =========================================================================
    "BAR_HOLDS": "CARRY",
    "CARRY": "CARRY",
    "WEIGHTED_CARRY": "CARRY",
    "FARMERS_CARRY": "CARRY",
    "FARMERS_WALK_CARRY": "CARRY",
    "FARMERS_WALK_ON_TOES": "CARRY",
    "HEX_DUMBBELL_HOLD": "CARRY",
    "KETTLEBELL_CARRY": "CARRY",
    "OVERHEAD_CARRY": "CARRY",
    "OVERHEAD_FARMERS_WALK": "CARRY",
    "OVERHEAD_WALK": "CARRY",
    "SANDBAG_CARRY": "CARRY",
    "SLED_DRAG": "CARRY",
    "SUITCASE_CARRY_CARRY": "CARRY",
    "TRAP_BAR_CARRY": "CARRY",
    "YOKE_CARRY": "CARRY",
    "RACK_CARRY": "CARRY",
    "ZERCHER_CARRY": "CARRY",
    "FRONT_RACK_CARRY": "CARRY",
    "WAITER_CARRY": "CARRY",
    "CROSS_BODY_CARRY": "CARRY",
    # =========================================================================
    # HIP_SWING Category
    # =========================================================================
    "HIP_SWING": "HIP_SWING",
    "WEIGHTED_HIP_SWING": "HIP_SWING",
    "INSIDE_OUT": "HIP_SWING",
    "SINGLE_ARM_SWING": "HIP_SWING",
    "SINGLE_LEG_HIP_SWING": "HIP_SWING",
    "STEP_OUT_SWING": "HIP_SWING",
    "SWING": "HIP_SWING",
    "KETTLEBELL_HIP_SWING": "HIP_SWING",
    "AMERICAN_KETTLEBELL_SWING": "HIP_SWING",
    "RUSSIAN_KETTLEBELL_SWING": "HIP_SWING",
    "ALTERNATING_KETTLEBELL_SWING": "HIP_SWING",
    "SINGLE_ARM_KETTLEBELL_SWING": "HIP_SWING",
    # =========================================================================
    # SHOULDER_STABILITY Category
    # =========================================================================
    "90_DEGREE_CABLE_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "BAND_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "BAND_INTERNAL_ROTATION": "SHOULDER_STABILITY",
    "BENT_ARM_LATERAL_RAISE_AND_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "CABLE_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "DUMBBELL_FACE_PULL_WITH_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "FLOOR_I_RAISE": "SHOULDER_STABILITY",
    "FLOOR_T_RAISE": "SHOULDER_STABILITY",
    "FLOOR_Y_RAISE": "SHOULDER_STABILITY",
    "INCLINE_I_RAISE": "SHOULDER_STABILITY",
    "INCLINE_L_RAISE": "SHOULDER_STABILITY",
    "INCLINE_T_RAISE": "SHOULDER_STABILITY",
    "INCLINE_W_RAISE": "SHOULDER_STABILITY",
    "INCLINE_Y_RAISE": "SHOULDER_STABILITY",
    "LYING_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "LYING_FLOOR_Y_RAISE": "SHOULDER_STABILITY",
    "PLANK_I_RAISE": "SHOULDER_STABILITY",
    "PRONE_I_RAISE": "SHOULDER_STABILITY",
    "PRONE_L_RAISE": "SHOULDER_STABILITY",
    "PRONE_T_RAISE": "SHOULDER_STABILITY",
    "PRONE_W_RAISE": "SHOULDER_STABILITY",
    "PRONE_Y_RAISE": "SHOULDER_STABILITY",
    "QUADRUPED_I_RAISE": "SHOULDER_STABILITY",
    "QUADRUPED_Y_RAISE": "SHOULDER_STABILITY",
    "SEATED_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "SHOULDER_STABILITY": "SHOULDER_STABILITY",
    "WEIGHTED_SHOULDER_STABILITY": "SHOULDER_STABILITY",
    "SIDE_LYING_EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "STANDING_L_RAISE": "SHOULDER_STABILITY",
    "SWISS_BALL_I_RAISE": "SHOULDER_STABILITY",
    "SWISS_BALL_T_RAISE": "SHOULDER_STABILITY",
    "SWISS_BALL_W_RAISE": "SHOULDER_STABILITY",
    "SWISS_BALL_Y_RAISE": "SHOULDER_STABILITY",
    "EXTERNAL_ROTATION": "SHOULDER_STABILITY",
    "INTERNAL_ROTATION": "SHOULDER_STABILITY",
    "CUBAN_ROTATION": "SHOULDER_STABILITY",
    "BAND_PULL_APART": "SHOULDER_STABILITY",
    "FACE_PULL_STABILITY": "SHOULDER_STABILITY",
    # =========================================================================
    # TOTAL_BODY Category
    # =========================================================================
    "BURPEE_TOTAL_BODY": "TOTAL_BODY",
    "WEIGHTED_BURPEE": "TOTAL_BODY",
    "BARBELL_BURPEE": "TOTAL_BODY",
    "BOX_JUMP_BURPEE": "TOTAL_BODY",
    "DUMBBELL_BURPEE": "TOTAL_BODY",
    "JUMPING_JACK": "TOTAL_BODY",
    "MAN_MAKER": "TOTAL_BODY",
    "MODIFIED_BURPEE": "TOTAL_BODY",
    "PULL_BURPEE": "TOTAL_BODY",
    "TURKISH_GET_UP_TOTAL_BODY": "TOTAL_BODY",
    "WALL_BALL_BURPEE": "TOTAL_BODY",
    "HIGH_KNEES": "TOTAL_BODY",
    "BUTT_KICKS": "TOTAL_BODY",
    "JUMPING_JACKS": "TOTAL_BODY",
    "DEVIL_PRESS": "TOTAL_BODY",
    "BURPEE_TO_BOX_JUMP": "TOTAL_BODY",
    "BATTLE_ROPE": "TOTAL_BODY",
    "BATTLE_ROPE_SLAM": "TOTAL_BODY",
    "BATTLE_ROPE_WAVE": "TOTAL_BODY",
    # =========================================================================
    # WARM_UP Category
    # =========================================================================
    "ARM_SWINGS": "WARM_UP",
    "LEG_SWINGS": "WARM_UP",
    "HIP_CIRCLES_WARM_UP": "WARM_UP",
    "TORSO_TWIST": "WARM_UP",
    "WALKING_HIGH_KNEES": "WARM_UP",
    "WALKING_QUAD_STRETCH": "WARM_UP",
    "WALKING_TOE_TOUCH": "WARM_UP",
    "WORLD_GREATEST_STRETCH": "WARM_UP",
    "INCHWORM_WARM_UP": "WARM_UP",
    "CAT_COW": "WARM_UP",
    "DOWNWARD_DOG": "WARM_UP",
    "HIP_OPENER": "WARM_UP",
    "THORACIC_ROTATION": "WARM_UP",
    "ANKLE_CIRCLES": "WARM_UP",
    "WRIST_CIRCLES": "WARM_UP",
    "NECK_CIRCLES": "WARM_UP",
    "SHOULDER_CIRCLES": "WARM_UP",
    "DYNAMIC_STRETCH": "WARM_UP",
    "WARM_UP": "WARM_UP",
    # =========================================================================
    # CARDIO Category
    # =========================================================================
    "BIKE": "CARDIO",
    "RUN": "CARDIO",
    "ROWING": "CARDIO",
    "ELLIPTICAL": "CARDIO",
    "STAIR_CLIMBER": "CARDIO",
    "SKI_ERG": "CARDIO",
    "ASSAULT_BIKE": "CARDIO",
    "AIR_BIKE": "CARDIO",
    "SPIN_BIKE": "CARDIO",
    "TREADMILL": "CARDIO",
    "STATIONARY_BIKE": "CARDIO",
    "RECUMBENT_BIKE": "CARDIO",
    "JUMP_ROPE": "CARDIO",
    "DOUBLE_UNDERS": "CARDIO",
    "SINGLE_UNDERS": "CARDIO",
    "SPRINTS": "CARDIO",
    "CARDIO": "CARDIO",
    # =========================================================================
    # SUSPENSION Category (TRX)
    # =========================================================================
    "TRX_BICEPS_CURL": "SUSPENSION",
    "TRX_CHEST_PRESS": "SUSPENSION",
    "TRX_FACE_PULL": "SUSPENSION",
    "TRX_HAMSTRING_CURL": "SUSPENSION",
    "TRX_HIP_PRESS": "SUSPENSION",
    "TRX_MOUNTAIN_CLIMBER": "SUSPENSION",
    "TRX_PIKE": "SUSPENSION",
    "TRX_PLANK": "SUSPENSION",
    "TRX_PULL_UP": "SUSPENSION",
    "TRX_PUSH_UP": "SUSPENSION",
    "TRX_ROW": "SUSPENSION",
    "TRX_SINGLE_LEG_SQUAT": "SUSPENSION",
    "TRX_SQUAT": "SUSPENSION",
    "TRX_TRICEPS_EXTENSION": "SUSPENSION",
    "TRX_Y_FLY": "SUSPENSION",
    "SUSPENSION_TRAINING": "SUSPENSION",
    # =========================================================================
    # OTHER / MISCELLANEOUS
    # =========================================================================
    "REST": "REST",
    "RECOVERY": "RECOVERY",
    "STRETCH": "FLEXIBILITY",
    "FOAM_ROLL": "FLEXIBILITY",
    "MOBILITY": "FLEXIBILITY",
    "YOGA": "FLEXIBILITY",
    "PILATES": "FLEXIBILITY",
}

# =============================================================================
# COMMON ALIASES
# =============================================================================
# Maps common user terms to their preferred Garmin exercise name
# Used to resolve ambiguous terms to the most common variant
# =============================================================================

ALIASES: Dict[str, str] = {
    # =========================================================================
    # Ambiguous terms → Most common variant (usually barbell)
    # =========================================================================
    "bench press": "BARBELL_BENCH_PRESS",
    "bench": "BARBELL_BENCH_PRESS",
    "deadlift": "BARBELL_DEADLIFT",
    "squat": "BARBELL_BACK_SQUAT",
    "back squat": "BARBELL_BACK_SQUAT",
    "front squat": "BARBELL_FRONT_SQUAT",
    "overhead press": "BARBELL_SHOULDER_PRESS",
    "shoulder press": "BARBELL_SHOULDER_PRESS",
    "military press": "BARBELL_SHOULDER_PRESS",
    "press": "BARBELL_SHOULDER_PRESS",
    "row": "BARBELL_ROW",
    "bent over row": "BENT_OVER_ROW_WITH_BARBELL",
    "curl": "BARBELL_BICEPS_CURL",
    "bicep curl": "BARBELL_BICEPS_CURL",
    "biceps curl": "BARBELL_BICEPS_CURL",
    "tricep extension": "TRICEPS_EXTENSION",
    "lunge": "BARBELL_LUNGE",
    "calf raise": "STANDING_CALF_RAISE",
    "shrug": "BARBELL_SHRUG",
    "upright row": "BARBELL_UPRIGHT_ROW",
    "hip thrust": "BARBELL_HIP_THRUST",
    "glute bridge": "GLUTE_BRIDGE",
    # =========================================================================
    # Common abbreviations and shorthand
    # =========================================================================
    "db": "DUMBBELL",
    "bb": "BARBELL",
    "kb": "KETTLEBELL",
    "ez": "EZ_BAR",
    "rdl": "ROMANIAN_DEADLIFT",
    "sldl": "STRAIGHT_LEG_DEADLIFT",
    "ohp": "OVERHEAD_PRESS",
    "bp": "BARBELL_BENCH_PRESS",
    "dl": "BARBELL_DEADLIFT",
    "sq": "BARBELL_BACK_SQUAT",
    "cgbp": "CLOSE_GRIP_BARBELL_BENCH_PRESS",
    "jm press": "JM_PRESS",
    "ghd": "GHD_SIT_UP",
    "ghr": "GLUTE_HAM_RAISE",
    # =========================================================================
    # Common exercise names (friendly format)
    # =========================================================================
    "lat pulldown": "LAT_PULLDOWN",
    "pulldown": "LAT_PULLDOWN",
    "pull up": "PULL_UP",
    "pullup": "PULL_UP",
    "pull-up": "PULL_UP",
    "chin up": "CHIN_UP",
    "chinup": "CHIN_UP",
    "chin-up": "CHIN_UP",
    "push up": "PUSH_UP",
    "pushup": "PUSH_UP",
    "push-up": "PUSH_UP",
    "dip": "TRICEPS_DIP",
    "dips": "TRICEPS_DIP",
    "skull crusher": "SKULL_CRUSHER",
    "skullcrusher": "SKULL_CRUSHER",
    "skull crushers": "SKULL_CRUSHER",
    "tricep pushdown": "TRICEPS_PUSHDOWN",
    "pushdown": "TRICEPS_PUSHDOWN",
    "cable pushdown": "TRICEPS_PUSHDOWN",
    "hammer curl": "DUMBBELL_HAMMER_CURL",
    "preacher curl": "EZ_BAR_PREACHER_CURL",
    "concentration curl": "ONE_ARM_CONCENTRATION_CURL",
    "incline curl": "INCLINE_DUMBBELL_BICEPS_CURL",
    "cable curl": "CABLE_BICEPS_CURL",
    "face pull": "FACE_PULL",
    "facepull": "FACE_PULL",
    "face pulls": "FACE_PULL",
    "lateral raise": "DUMBBELL_LATERAL_RAISE",
    "side raise": "DUMBBELL_LATERAL_RAISE",
    "side lateral raise": "DUMBBELL_LATERAL_RAISE",
    "front raise": "DUMBBELL_FRONT_RAISE",
    "rear delt fly": "REAR_DELT_FLY",
    "reverse fly": "REVERSE_FLY",
    "cable fly": "CABLE_FLY",
    "chest fly": "DUMBBELL_FLYE",
    "pec deck": "PEC_DECK",
    "cable crossover": "CABLE_CROSSOVER",
    "seated row": "SEATED_CABLE_ROW",
    "cable row": "SEATED_CABLE_ROW",
    "t bar row": "T_BAR_ROW",
    "t-bar row": "T_BAR_ROW",
    "pendlay row": "PENDLAY_ROW",
    "leg press": "LEG_PRESS",
    "leg curl": "LYING_LEG_CURL",
    "hamstring curl": "LYING_LEG_CURL",
    "leg extension": "LEG_EXTENSIONS",
    "quad extension": "LEG_EXTENSIONS",
    "hip abduction": "HIP_ABDUCTION_MACHINE",
    "hip adduction": "HIP_ADDUCTION_MACHINE",
    "goblet squat": "GOBLET_SQUAT",
    "sumo squat": "SUMO_SQUAT",
    "hack squat": "BARBELL_HACK_SQUAT",
    "box squat": "BARBELL_BOX_SQUAT",
    "bulgarian split squat": "DUMBBELL_BULGARIAN_SPLIT_SQUAT",
    "split squat": "DUMBBELL_SPLIT_SQUAT",
    "step up": "DUMBBELL_STEP_UP",
    "step-up": "DUMBBELL_STEP_UP",
    "walking lunge": "WALKING_DUMBBELL_LUNGE",
    "reverse lunge": "DUMBBELL_REVERSE_LUNGE",
    "forward lunge": "DUMBBELL_LUNGE",
    "side lunge": "SIDE_LUNGE",
    "lateral lunge": "LATERAL_LUNGE",
    "good morning": "BARBELL_GOOD_MORNING",
    "romanian deadlift": "ROMANIAN_DEADLIFT",
    "stiff leg deadlift": "STRAIGHT_LEG_DEADLIFT",
    "sumo deadlift": "SUMO_DEADLIFT",
    "trap bar deadlift": "TRAP_BAR_DEADLIFT",
    "rack pull": "RACK_PULL",
    "clean": "BARBELL_POWER_CLEAN",
    "power clean": "BARBELL_POWER_CLEAN",
    "hang clean": "BARBELL_HANG_CLEAN",
    "snatch": "BARBELL_SNATCH",
    "power snatch": "BARBELL_POWER_SNATCH",
    "clean and jerk": "BARBELL_CLEAN_AND_JERK",
    "thruster": "THRUSTERS",
    "thrusters": "THRUSTERS",
    "wall ball": "WALL_BALL",
    "kettlebell swing": "KETTLEBELL_SWING",
    "kb swing": "KETTLEBELL_SWING",
    "turkish get up": "TURKISH_GET_UP",
    "tgu": "TURKISH_GET_UP",
    "farmers walk": "FARMERS_WALK",
    "farmers carry": "FARMERS_CARRY",
    "suitcase carry": "SUITCASE_CARRY",
    "plank": "PLANK",
    "side plank": "SIDE_PLANK",
    "mountain climber": "MOUNTAIN_CLIMBER",
    "mountain climbers": "MOUNTAIN_CLIMBER",
    "burpee": "BURPEE",
    "burpees": "BURPEE",
    "box jump": "BOX_JUMP",
    "box jumps": "BOX_JUMP",
    "jump squat": "JUMP_SQUAT",
    "jump squats": "JUMP_SQUAT",
    "tuck jump": "TUCK_JUMP",
    "broad jump": "BROAD_JUMP",
    "crunch": "CRUNCH",
    "crunches": "CRUNCH",
    "sit up": "SIT_UP",
    "situp": "SIT_UP",
    "sit-up": "SIT_UP",
    "leg raise": "HANGING_LEG_RAISE",
    "hanging leg raise": "HANGING_LEG_RAISE",
    "russian twist": "RUSSIAN_TWIST",
    "v up": "V_UP",
    "v-up": "V_UP",
    "bicycle crunch": "BICYCLE_CRUNCH",
    "dead bug": "DEAD_BUG",
    "bird dog": "BIRD_DOG",
    "superman": "SUPERMAN",
    "back extension": "BACK_EXTENSION",
    "hyperextension": "HYPEREXTENSION",
    "ab wheel": "AB_WHEEL_ROLLOUT",
    "ab roller": "AB_WHEEL_ROLLOUT",
    "pallof press": "PALLOF_PRESS",
    "woodchop": "CABLE_WOODCHOP",
    "wood chop": "CABLE_WOODCHOP",
    "hollow hold": "HOLLOW_BODY_HOLD",
    "hollow body": "HOLLOW_BODY_HOLD",
    "arnold press": "ARNOLD_PRESS",
    "incline press": "INCLINE_BARBELL_BENCH_PRESS",
    "incline bench": "INCLINE_BARBELL_BENCH_PRESS",
    "decline press": "DECLINE_DUMBBELL_BENCH_PRESS",
    "decline bench": "DECLINE_DUMBBELL_BENCH_PRESS",
    "floor press": "BARBELL_FLOOR_PRESS",
    "close grip bench": "CLOSE_GRIP_BARBELL_BENCH_PRESS",
    "close grip bench press": "CLOSE_GRIP_BARBELL_BENCH_PRESS",
    "wide grip bench": "WIDE_GRIP_BARBELL_BENCH_PRESS",
    "pause squat": "PAUSE_SQUAT",
    "box step up": "BOX_STEP_SQUAT",
    "pistol squat": "PISTOL_SQUAT",
    "pistol": "PISTOL_SQUAT",
    "clamshell": "CLAMSHELL",
    "clam": "CLAMSHELL",
    "hip circle": "HIP_CIRCLES",
    "band walk": "BANDED_LATERAL_WALK",
    "monster walk": "BANDED_MONSTER_WALK",
    "glute kickback": "QUADRUPED_HIP_EXTENSION",
    "donkey kick": "QUADRUPED_HIP_EXTENSION",
    "fire hydrant": "FIRE_HYDRANT",
    "jumping jack": "JUMPING_JACKS",
    "jumping jacks": "JUMPING_JACKS",
    "high knees": "HIGH_KNEES",
    "butt kicks": "BUTT_KICKS",
    "jump rope": "JUMP_ROPE",
    "double under": "DOUBLE_UNDERS",
    "double unders": "DOUBLE_UNDERS",
    "battle rope": "BATTLE_ROPE",
    "battle ropes": "BATTLE_ROPE",
    "rowing": "ROWING",
    "row machine": "ROWING",
    "rower": "ROWING",
    "bike": "BIKE",
    "assault bike": "ASSAULT_BIKE",
    "air bike": "AIR_BIKE",
    "ski erg": "SKI_ERG",
    "elliptical": "ELLIPTICAL",
    "treadmill": "TREADMILL",
    "stair climber": "STAIR_CLIMBER",
    "rest": "REST",
    "recovery": "RECOVERY",
    "stretch": "STRETCH",
    "foam roll": "FOAM_ROLL",
}

# =============================================================================
# EQUIPMENT PREFIXES
# =============================================================================

EQUIPMENT_PREFIXES: Set[str] = {
    "BARBELL",
    "DUMBBELL",
    "KETTLEBELL",
    "CABLE",
    "MACHINE",
    "BODYWEIGHT",
    "BAND",
    "MEDICINE_BALL",
    "SWISS_BALL",
    "EZ_BAR",
    "TRAP_BAR",
    "SMITH_MACHINE",
    "LANDMINE",
    "SUSPENSION",
    "WEIGHTED",
    "ALTERNATING",
    "SINGLE_ARM",
    "SINGLE_LEG",
    "ONE_ARM",
    "ONE_LEG",
    "SEATED",
    "STANDING",
    "INCLINE",
    "DECLINE",
    "FLAT",
    "REVERSE",
    "WIDE_GRIP",
    "CLOSE_GRIP",
    "NEUTRAL_GRIP",
}


class ExerciseMatcher:
    """Fuzzy matcher for Garmin exercise names.

    Converts user-friendly exercise names to Garmin's SCREAMING_SNAKE_CASE format
    using a hybrid approach of alias lookup, token matching, and Levenshtein distance.

    Example:
        >>> matcher = ExerciseMatcher()
        >>> result = matcher.resolve("dumbbell bench press")
        >>> result.name
        'DUMBBELL_BENCH_PRESS'

        >>> result = matcher.resolve("dumbell curl")  # typo handled
        >>> result.name
        'DUMBBELL_BICEPS_CURL'

        >>> results = matcher.search("squat", limit=5)
        >>> [r.name for r in results]
        ['BARBELL_SQUAT', 'GOBLET_SQUAT', 'FRONT_SQUAT', ...]
    """

    def __init__(self, threshold: float = 0.5) -> None:
        """Initialize the exercise matcher.

        Args:
            threshold: Minimum confidence score (0-1) to return a match.
                      Default 0.5 balances precision and recall.
        """
        self._threshold = threshold
        self._exercises = EXERCISES
        self._aliases = ALIASES
        self._exercise_names = list(EXERCISES.keys())
        self._normalized_index: Dict[str, str] = {}
        self._build_index()

    def _build_index(self) -> None:
        """Build normalized index for fast lookup."""
        for name in self._exercise_names:
            normalized = self._normalize(name)
            self._normalized_index[normalized] = name

    @staticmethod
    def _normalize(text: str) -> str:
        """Normalize text for matching.

        Converts to lowercase, removes punctuation, replaces spaces with underscores.
        """
        text = text.lower().strip()
        text = re.sub(r"[^\w\s]", "", text)
        text = re.sub(r"\s+", "_", text)
        return text

    @staticmethod
    def _tokenize(text: str) -> Set[str]:
        """Extract tokens from text."""
        normalized = ExerciseMatcher._normalize(text)
        return set(normalized.split("_"))

    @staticmethod
    def _levenshtein_ratio(s1: str, s2: str) -> float:
        """Calculate similarity ratio using SequenceMatcher."""
        return SequenceMatcher(None, s1, s2).ratio()

    def _score_candidate(
        self, query_tokens: Set[str], candidate: str, query_normalized: str
    ) -> float:
        """Score a candidate exercise against the query.

        Uses a combination of:
        1. Exact normalized match
        2. Token overlap (Jaccard similarity)
        3. Fuzzy token matching (Levenshtein)
        4. Overall string similarity
        """
        candidate_normalized = self._normalize(candidate)
        candidate_tokens = self._tokenize(candidate)

        # Exact match after normalization
        if query_normalized == candidate_normalized:
            return 1.0

        # Token overlap score (Jaccard)
        intersection = query_tokens & candidate_tokens
        union = query_tokens | candidate_tokens
        token_score = len(intersection) / len(union) if union else 0

        # Fuzzy token matching - find best match for each query token
        fuzzy_scores = []
        for qt in query_tokens:
            if qt in candidate_tokens:
                fuzzy_scores.append(1.0)
            else:
                best = max(
                    (self._levenshtein_ratio(qt, ct) for ct in candidate_tokens),
                    default=0,
                )
                fuzzy_scores.append(best)
        fuzzy_score = sum(fuzzy_scores) / len(fuzzy_scores) if fuzzy_scores else 0

        # Overall string similarity
        string_score = self._levenshtein_ratio(query_normalized, candidate_normalized)

        # Weighted combination
        # Token overlap is most important, then fuzzy tokens, then overall string
        return (token_score * 0.4) + (fuzzy_score * 0.4) + (string_score * 0.2)

    def resolve(
        self, query: str, equipment_hint: Optional[str] = None
    ) -> Optional[MatchResult]:
        """Find the best matching Garmin exercise name.

        Args:
            query: User-provided exercise name (any format)
            equipment_hint: Optional equipment to prefer (e.g., "dumbbell")

        Returns:
            MatchResult if confidence >= threshold, else None
        """
        if not query or not query.strip():
            return None

        query_normalized = self._normalize(query)
        query_tokens = self._tokenize(query)

        # 1. Check exact match in index
        if query_normalized in self._normalized_index:
            name = self._normalized_index[query_normalized]
            return MatchResult(
                name=name,
                category=self._exercises[name],
                score=1.0,
            )

        # 2. Check aliases
        query_lower = query.lower().strip()
        if query_lower in self._aliases:
            name = self._aliases[query_lower]
            if name in self._exercises:
                return MatchResult(
                    name=name,
                    category=self._exercises[name],
                    score=0.95,  # High confidence for alias match
                )

        # 3. Score all candidates
        candidates: List[Tuple[str, float]] = []
        for exercise_name in self._exercise_names:
            score = self._score_candidate(query_tokens, exercise_name, query_normalized)

            # Apply equipment hint bonus
            if equipment_hint:
                hint_normalized = self._normalize(equipment_hint)
                if hint_normalized.upper() in exercise_name:
                    score = min(1.0, score + 0.15)

            candidates.append((exercise_name, score))

        # Sort by score descending
        candidates.sort(key=lambda x: x[1], reverse=True)

        if not candidates or candidates[0][1] < self._threshold:
            return None

        best_name, best_score = candidates[0]

        # Get alternatives (top 5 excluding best)
        alternatives = [
            (name, self._exercises[name], score)
            for name, score in candidates[1:6]
            if score >= self._threshold
        ]

        return MatchResult(
            name=best_name,
            category=self._exercises[best_name],
            score=best_score,
            alternatives=alternatives,
        )

    def resolve_or_raise(
        self, query: str, equipment_hint: Optional[str] = None
    ) -> MatchResult:
        """Resolve exercise name or raise ValueError with suggestions.

        Args:
            query: User-provided exercise name
            equipment_hint: Optional equipment preference

        Returns:
            MatchResult for the best match

        Raises:
            ValueError: If no match found, includes suggestions
        """
        result = self.resolve(query, equipment_hint)
        if result is None:
            suggestions = self.search(query, limit=3)
            if suggestions:
                suggestion_str = ", ".join(r.name for r in suggestions)
                raise ValueError(
                    f"No match found for '{query}'. Did you mean: {suggestion_str}?"
                )
            else:
                raise ValueError(
                    f"No match found for '{query}'. "
                    f"Use search_exercises to find valid exercise names."
                )
        return result

    def search(self, query: str, limit: int = 10) -> List[MatchResult]:
        """Search for exercises matching the query.

        Args:
            query: Search term
            limit: Maximum number of results

        Returns:
            List of MatchResult sorted by score descending
        """
        if not query or not query.strip():
            return []

        query_normalized = self._normalize(query)
        query_tokens = self._tokenize(query)

        # Score all candidates
        candidates: List[Tuple[str, float]] = []
        for exercise_name in self._exercise_names:
            score = self._score_candidate(query_tokens, exercise_name, query_normalized)
            candidates.append((exercise_name, score))

        # Sort by score and take top N
        candidates.sort(key=lambda x: x[1], reverse=True)
        top_candidates = candidates[:limit]

        return [
            MatchResult(
                name=name,
                category=self._exercises[name],
                score=score,
            )
            for name, score in top_candidates
            if score > 0
        ]

    def get_category(self, exercise_name: str) -> Optional[str]:
        """Get the category for a Garmin exercise name.

        Args:
            exercise_name: Exercise name in any format

        Returns:
            Category name or None if not found
        """
        # Try exact match first
        if exercise_name in self._exercises:
            return self._exercises[exercise_name]

        # Try normalized match
        normalized = self._normalize(exercise_name)
        if normalized in self._normalized_index:
            name = self._normalized_index[normalized]
            return self._exercises[name]

        return None

    def list_categories(self) -> List[str]:
        """List all unique exercise categories."""
        return sorted(set(self._exercises.values()))

    def list_by_category(self, category: str) -> List[str]:
        """List all exercises in a category.

        Args:
            category: Category name (case-insensitive)

        Returns:
            List of exercise names in the category
        """
        category_upper = category.upper()
        return sorted(
            name for name, cat in self._exercises.items() if cat == category_upper
        )

    def list_by_equipment(self, equipment: str) -> List[str]:
        """List all exercises for an equipment type.

        Args:
            equipment: Equipment prefix (e.g., "DUMBBELL", "BARBELL")

        Returns:
            List of exercise names using that equipment
        """
        equipment_upper = equipment.upper()
        return sorted(
            name for name in self._exercise_names if name.startswith(equipment_upper)
        )


# =============================================================================
# MODULE-LEVEL CONVENIENCE FUNCTIONS
# =============================================================================

_default_matcher: Optional[ExerciseMatcher] = None


def get_matcher() -> ExerciseMatcher:
    """Get or create the default ExerciseMatcher instance."""
    global _default_matcher
    if _default_matcher is None:
        _default_matcher = ExerciseMatcher()
    return _default_matcher


def resolve_exercise(
    query: str, equipment_hint: Optional[str] = None
) -> Tuple[str, str]:
    """Resolve a user-friendly exercise name to Garmin format.

    Convenience function that returns (exercise_name, category) tuple.

    Args:
        query: User-provided exercise name
        equipment_hint: Optional equipment preference

    Returns:
        Tuple of (garmin_name, category)

    Raises:
        ValueError: If no match found
    """
    result = get_matcher().resolve_or_raise(query, equipment_hint)
    return result.name, result.category


def search_exercises(query: str, limit: int = 10) -> List[MatchResult]:
    """Search for exercises matching the query.

    Convenience function for exercise discovery.

    Args:
        query: Search term
        limit: Maximum results

    Returns:
        List of MatchResult
    """
    return get_matcher().search(query, limit)
